function df_u_u_uai = df_u_u_uai
%DF_U_U_UAI
%    DF_U_U_UAI = DF_U_U_UAI

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:12

df_u_u_uai = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[3,2]);
