function dg_q_xhi_gammaxhi = dg_q_xhi_gammaxhi(in1,in2)
%DG_Q_XHI_GAMMAXHI
%    DG_Q_XHI_GAMMAXHI = DG_Q_XHI_GAMMAXHI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:14

dg_q_xhi_gammaxhi = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
