function func = dgq_a2x(t,theta)
%DGQ_A2X
%    FUNC = DGQ_A2X(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:28

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.*6.0+t.^2.*2.0+2.0))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
