function func = dgq_a2x(t,theta)
%DGQ_A2X
%    FUNC = DGQ_A2X(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:21

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.*4.0+t.^2.*3.0+2.0))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
