function func = dgq_a1y(t,theta)
%DGQ_A1Y
%    FUNC = DGQ_A1Y(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:22

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*(t.*6.0+t.^2.*6.0+t.^3.*3.0))./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
