function func = dgq_a4x(theta)
%DGQ_A4X
%    FUNC = DGQ_A4X(THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:22

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*-3.0)./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
