function func = dgxhi_a4x
%DGXHI_A4X
%    FUNC = DGXHI_A4X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:29

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
