function func = dgxhi_a4y
%DGXHI_A4Y
%    FUNC = DGXHI_A4Y

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:24

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
