function func = dgxhi_a1y
%DGXHI_A1Y
%    FUNC = DGXHI_A1Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:54

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
