function func = dgxhi_a2x
%DGXHI_A2X
%    FUNC = DGXHI_A2X

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:23

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
