function func = dgxhi_a1y
%DGXHI_A1Y
%    FUNC = DGXHI_A1Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:29

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
