function dh_q_xhi_gammaxhi = dh_q_xhi_gammaxhi(in1,in2,in3,in4,in5,in6)
%DH_Q_XHI_GAMMAXHI
%    DH_Q_XHI_GAMMAXHI = DH_Q_XHI_GAMMAXHI(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:24

ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t10 = t2.^2;
t11 = t3.^2;
t12 = -t6;
t13 = -t8;
t14 = t2.*xhi_v.*3.0;
t15 = t3.*xhi_v.*3.0;
t16 = t10.*xhi_v;
t17 = t11.*xhi_v;
t18 = -t14;
t19 = -t15;
t20 = t10+t11;
t21 = t16+t17;
t24 = ddx_d+t4+t7+t12+t18+xhi_x;
t25 = ddy_d+t5+t9+t13+t19+xhi_y;
t22 = 1.0./t21;
t23 = t22.^2;
t26 = g2.*t2.*t22.*2.920443101711984;
t27 = g3.*t3.*t22.*2.920443101711984;
t28 = g1.*t2.*t20.*t23.*5.840886203423968;
t29 = g1.*t3.*t20.*t23.*5.840886203423968;
t30 = t16.*t20.*t23.*8.761329305135952;
t31 = t17.*t20.*t23.*8.761329305135952;
t32 = t2.*t20.*t23.*t24.*2.920443101711984;
t33 = t3.*t20.*t23.*t25.*2.920443101711984;
t34 = t30+t31+t32+t33;
t35 = g1.*t34;
dh_q_xhi_gammaxhi = reshape([-t29,t29,t28,-t28,-t26-t27+t35,t26+t27-t35],[2,3]);
end
