function dh_q_q_gamma = dh_q_q_gamma(in1,in2,in3,in4,in5,in6)
%DH_Q_Q_GAMMA
%    DH_Q_Q_GAMMA = DH_Q_Q_GAMMA(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:12

ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*2.0;
t5 = dy_d.*2.0;
t6 = x.*3.0;
t7 = x_d.*3.0;
t8 = y.*3.0;
t9 = y_d.*3.0;
t10 = t2.^2;
t11 = t3.^2;
t12 = -t6;
t13 = -t8;
t14 = t2.*xhi_v.*2.0;
t15 = t3.*xhi_v.*2.0;
t16 = t10.*xhi_v;
t17 = t11.*xhi_v;
t18 = -t14;
t19 = -t15;
t20 = t16+t17;
t22 = ddx_d+t4+t7+t12+t18;
t23 = ddy_d+t5+t9+t13+t19;
t21 = 1.0./t20;
t24 = g1.*t2.*t21.*1.2e+1;
t25 = g3.*t2.*t21.*1.2e+1;
t26 = g2.*t3.*t21.*1.2e+1;
t27 = g3.*t3.*t21.*1.2e+1;
t28 = t3.*t21.*t22.*4.0;
t29 = t2.*t21.*t23.*4.0;
t30 = -t29;
t31 = t28+t30;
t32 = g3.*t31;
dh_q_q_gamma = reshape([t25,-t25,t27,-t27,t24+t26+t32,-t24-t26-t32],[2,3]);
