function func = dhq_a4x(theta,xhi_v)
%DHQ_A4X
%    FUNC = DHQ_A4X(THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:51

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4.*xhi_v;
t7 = t5.*xhi_v;
t8 = t6+t7;
t9 = 1.0./t8;
t10 = t2.*t9.*5.840886203423968;
func = reshape([0.0,0.0,0.0,0.0,-t10,t10],[2,3]);
end
