function func = dhq_a1x(t,theta,xhi_v)
%DHQ_A1X
%    FUNC = DHQ_A1X(T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:16

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t7 = t2.^2;
t8 = t3.^2;
t9 = t6.*3.0;
t10 = t.*t4;
t11 = t7.*xhi_v;
t12 = t8.*xhi_v;
t14 = t4+t9+t10;
t13 = t11+t12;
t15 = 1.0./t13;
t16 = t2.*t14.*t15.*4.0;
func = reshape([0.0,0.0,0.0,0.0,-t16,t16],[2,3]);
