function func = dhq_a4y(theta,xhi_v)
%DHQ_A4Y
%    FUNC = DHQ_A4Y(THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:18

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4.*xhi_v;
t7 = t5.*xhi_v;
t8 = t6+t7;
t9 = 1.0./t8;
t10 = t3.*t9.*1.2e+1;
func = reshape([0.0,0.0,0.0,0.0,-t10,t10],[2,3]);
