function func = dhq_a3y(t,theta,xhi_v)
%DHQ_A3Y
%    FUNC = DHQ_A3Y(T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:26

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*2.0;
t5 = t2.^2;
t6 = t3.^2;
t7 = t4+3.0;
t8 = t5.*xhi_v;
t9 = t6.*xhi_v;
t10 = t8+t9;
t11 = 1.0./t10;
t12 = t3.*t7.*t11.*2.920443101711984;
func = reshape([0.0,0.0,0.0,0.0,-t12,t12],[2,3]);
end
