function func = dhq_a2x(t,theta,xhi_v)
%DHQ_A2X
%    FUNC = DHQ_A2X(T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:26

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t2.^2;
t7 = t3.^2;
t8 = t5.*2.0;
t9 = t6.*xhi_v;
t10 = t7.*xhi_v;
t11 = t4+t8+2.0;
t12 = t9+t10;
t13 = 1.0./t12;
t14 = t2.*t11.*t13.*2.920443101711984;
func = reshape([0.0,0.0,0.0,0.0,-t14,t14],[2,3]);
end
