function func = dhq_a1y(t,theta,xhi_v)
%DHQ_A1Y
%    FUNC = DHQ_A1Y(T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:26

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t7 = t2.^2;
t8 = t3.^2;
t9 = t6.*2.0;
t12 = t5.*9.0;
t10 = t7.*xhi_v;
t11 = t8.*xhi_v;
t14 = t4+t9+t12;
t13 = t10+t11;
t15 = 1.0./t13;
t16 = t3.*t14.*t15.*2.920443101711984;
func = reshape([0.0,0.0,0.0,0.0,-t16,t16],[2,3]);
end
