function func = dhxhi_a3x(t,theta,xhi_v)
%DHXHI_A3X
%    FUNC = DHXHI_A3X(T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:52

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*2.0;
t5 = t2.^2;
t6 = t3.^2;
t7 = t4+3.0;
t8 = t5.*xhi_v;
t9 = t6.*xhi_v;
t10 = t5+t6;
t11 = t8+t9;
t12 = 1.0./t11.^2;
t13 = t3.*t7.*t10.*t12.*2.920443101711984;
func = reshape([t13,-t13,0.0,0.0,0.0,0.0],[2,3]);
end
