function func = dhxhi_a1x(t,theta,xhi_v)
%DHXHI_A1X
%    FUNC = DHXHI_A1X(T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:19

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t7 = t2.^2;
t8 = t3.^2;
t9 = t6.*3.0;
t10 = t.*t4;
t11 = t7.*xhi_v;
t12 = t8.*xhi_v;
t13 = t7+t8;
t15 = t4+t9+t10;
t14 = t11+t12;
t16 = 1.0./t14.^2;
t17 = t3.*t13.*t15.*t16.*4.0;
func = reshape([t17,-t17,0.0,0.0,0.0,0.0],[2,3]);
