function func = dhxhi_a4x(theta,xhi_v)
%DHXHI_A4X
%    FUNC = DHXHI_A4X(THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:52

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4.*xhi_v;
t7 = t5.*xhi_v;
t8 = t4+t5;
t9 = t6+t7;
t10 = 1.0./t9.^2;
t11 = t3.*t8.*t10.*5.840886203423968;
func = reshape([t11,-t11,0.0,0.0,0.0,0.0],[2,3]);
end
