function func = dhxhi_a1y(t,theta,xhi_v)
%DHXHI_A1Y
%    FUNC = DHXHI_A1Y(T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:52

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t7 = t2.^2;
t8 = t3.^2;
t9 = t6.*2.0;
t12 = t5.*9.0;
t10 = t7.*xhi_v;
t11 = t8.*xhi_v;
t13 = t7+t8;
t15 = t4+t9+t12;
t14 = t10+t11;
t16 = 1.0./t14.^2;
t17 = t2.*t13.*t15.*t16.*2.920443101711984;
func = reshape([-t17,t17,0.0,0.0,0.0,0.0],[2,3]);
end
