function func = dhxhi_a2x(t,theta,xhi_v)
%DHXHI_A2X
%    FUNC = DHXHI_A2X(T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:19

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*4.0;
t5 = t.^2;
t6 = t2.^2;
t7 = t3.^2;
t8 = t5.*3.0;
t9 = t6.*xhi_v;
t10 = t7.*xhi_v;
t11 = t6+t7;
t12 = t4+t8+2.0;
t13 = t9+t10;
t14 = 1.0./t13.^2;
t15 = t3.*t11.*t12.*t14.*4.0;
func = reshape([t15,-t15,0.0,0.0,0.0,0.0],[2,3]);
