function h_q = fh_q(in1,in2,in3,in4,in5)
%FH_Q
%    H_Q = FH_Q(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:23

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t10 = t2.^2;
t11 = t3.^2;
t12 = -t6;
t13 = -t8;
t14 = t2.*xhi_v.*3.0;
t15 = t3.*xhi_v.*3.0;
t16 = t10.*xhi_v;
t17 = t11.*xhi_v;
t18 = -t14;
t19 = -t15;
t20 = t16+t17;
t22 = ddx_d+t4+t7+t12+t18+xhi_x;
t23 = ddy_d+t5+t9+t13+t19+xhi_y;
t21 = 1.0./t20;
t24 = t2.*t21.*5.840886203423968;
t25 = t3.*t21.*5.840886203423968;
t26 = t17.*t21.*8.761329305135952;
t27 = t16.*t21.*8.761329305135952;
t28 = t2.*t21.*t22.*2.920443101711984;
t29 = t3.*t21.*t23.*2.920443101711984;
h_q = reshape([t25,-t25,-t24,t24,-t26-t27-t28-t29,t26+t27+t28+t29],[2,3]);
end
