function h_xhi = fh_xhi(in1,in2,in3,in4,in5)
%FH_XHI
%    H_XHI = FH_XHI(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:47

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t10 = t2.^2;
t11 = t3.^2;
t12 = -t6;
t13 = -t8;
t14 = t2.*xhi_v.*3.0;
t15 = t3.*xhi_v.*3.0;
t16 = t10.*xhi_v;
t17 = t11.*xhi_v;
t18 = -t14;
t19 = -t15;
t20 = t10+t11;
t21 = t16+t17;
t24 = ddx_d+t4+t7+t12+t18+xhi_x;
t25 = ddy_d+t5+t9+t13+t19+xhi_y;
t22 = 1.0./t21;
t23 = t22.^2;
t26 = t2.*t22.*2.920443101711984;
t27 = t3.*t22.*2.920443101711984;
t28 = t3.*t20.*t23.*t24.*2.920443101711984;
t29 = t2.*t20.*t23.*t25.*2.920443101711984;
h_xhi = reshape([t28-t29+1.007049345417925e+1,-t28+t29+1.007049345417925e+1,-t27,t27,t26,-t26],[2,3]);
end
