function g_a_1x = g_a_1x(in1,t)
%G_A_1X
%    G_A_1X = G_A_1X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:16

theta = in1(3,:);
t2 = cos(theta);
t3 = t.^3;
g_a_1x = [(t2.*(t.*6.0+t3.*3.0+t.^2.*6.0))./(sin(theta).^2+t2.^2);t3;0.0];
