function g_a_2y = g_a_2y(in1,t)
%G_A_2Y
%    G_A_2Y = G_A_2Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:16

theta = in1(3,:);
t2 = sin(theta);
t3 = t.^2;
g_a_2y = [(t2.*(t.*4.0+t3.*3.0+2.0))./(cos(theta).^2+t2.^2);0.0;t3];
