function g_a_3y = g_a_3y(in1,t)
%G_A_3Y
%    G_A_3Y = G_A_3Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:16

theta = in1(3,:);
t2 = sin(theta);
g_a_3y = [(t2.*(t.*3.0+2.0))./(cos(theta).^2+t2.^2);0.0;t];
