function g_a_4y = g_a_4y(in1)
%G_A_4Y
%    G_A_4Y = G_A_4Y(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:16

theta = in1(3,:);
t2 = sin(theta);
g_a_4y = [(t2.*3.0)./(cos(theta).^2+t2.^2);0.0;1.0];
