function g_a_4x = g_a_4x(in1)
%G_A_4X
%    G_A_4X = G_A_4X(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:16

theta = in1(3,:);
t2 = cos(theta);
g_a_4x = [(t2.*3.0)./(sin(theta).^2+t2.^2);1.0;0.0];
