function g_a_3x = g_a_3x(in1,t)
%G_A_3X
%    G_A_3X = G_A_3X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:16

theta = in1(3,:);
t2 = cos(theta);
g_a_3x = [(t2.*(t.*3.0+2.0))./(sin(theta).^2+t2.^2);t;0.0];
