function h_a_2y = h_a_2y(in1,t,in3)
%H_A_2Y
%    H_A_2Y = H_A_2Y(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:50

theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t2.^2;
t7 = t3.^2;
t8 = t5.*2.0;
t9 = t6.*xhi_v;
t10 = t7.*xhi_v;
t11 = t4+t8+2.0;
t12 = t9+t10;
t13 = 1.0./t12;
t14 = t2.*t11.*t13.*2.920443101711984;
h_a_2y = [t14;-t14];
end
