function h_a_1y = h_a_1y(in1,t,in3)
%H_A_1Y
%    H_A_1Y = H_A_1Y(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:49

theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t7 = t2.^2;
t8 = t3.^2;
t9 = t6.*2.0;
t12 = t5.*9.0;
t10 = t7.*xhi_v;
t11 = t8.*xhi_v;
t14 = t4+t9+t12;
t13 = t10+t11;
t15 = 1.0./t13;
t16 = t2.*t14.*t15.*2.920443101711984;
h_a_1y = [t16;-t16];
end
