function h_a_1x = h_a_1x(in1,t,in3)
%H_A_1X
%    H_A_1X = H_A_1X(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:14

theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t7 = t2.^2;
t8 = t3.^2;
t9 = t6.*3.0;
t10 = t.*t4;
t11 = t7.*xhi_v;
t12 = t8.*xhi_v;
t14 = t4+t9+t10;
t13 = t11+t12;
t15 = 1.0./t13;
t16 = t3.*t14.*t15.*4.0;
h_a_1x = [-t16;t16];
