function h_a_4x = h_a_4x(in1,t,in3)
%H_A_4X
%    H_A_4X = H_A_4X(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:15

theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4.*xhi_v;
t7 = t5.*xhi_v;
t8 = t6+t7;
t9 = 1.0./t8;
t10 = t3.*t9.*1.2e+1;
h_a_4x = [-t10;t10];
