function h_a_3y = h_a_3y(in1,t,in3)
%H_A_3Y
%    H_A_3Y = H_A_3Y(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:15

theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*3.0;
t5 = t2.^2;
t6 = t3.^2;
t7 = t4+2.0;
t8 = t5.*xhi_v;
t9 = t6.*xhi_v;
t10 = t8+t9;
t11 = 1.0./t10;
t12 = t2.*t7.*t11.*4.0;
h_a_3y = [t12;-t12];
