function h_a_4y = h_a_4y(in1,t,in3)
%H_A_4Y
%    H_A_4Y = H_A_4Y(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:25

theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4.*xhi_v;
t7 = t5.*xhi_v;
t8 = t6+t7;
t9 = 1.0./t8;
t10 = t2.*t9.*5.840886203423968;
h_a_4y = [t10;-t10];
end
