function new_u = new_u(in1,in2,in3,in4,in5)
%NEW_U
%    NEW_U = NEW_U(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:10

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*2.0;
t5 = dy_d.*2.0;
t6 = x.*3.0;
t7 = x_d.*3.0;
t8 = xhi_v.*5.0;
t9 = y.*3.0;
t10 = y_d.*3.0;
t11 = t2.^2;
t12 = t3.^2;
t13 = -t6;
t14 = -t9;
t15 = t2.*xhi_v.*2.0;
t16 = t3.*xhi_v.*2.0;
t17 = t11.*xhi_v;
t18 = t12.*xhi_v;
t19 = -t15;
t20 = -t16;
t21 = t17+t18;
t23 = ddx_d+t4+t7+t13+t19;
t24 = ddy_d+t5+t10+t14+t20;
t22 = 1.0./t21;
t25 = t3.*t22.*t23.*4.0;
t26 = t2.*t22.*t24.*4.0;
new_u = [t8-t25+t26;t8+t25-t26];
