function new_u = new_u(in1,in2,in3,in4,in5)
%NEW_U
%    NEW_U = NEW_U(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:22

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t20 = xhi_v.*1.007049345417925e+1;
t10 = t2.^2;
t11 = t3.^2;
t12 = -t6;
t13 = -t8;
t14 = t2.*xhi_v.*3.0;
t15 = t3.*xhi_v.*3.0;
t16 = t10.*xhi_v;
t17 = t11.*xhi_v;
t18 = -t14;
t19 = -t15;
t21 = t16+t17;
t23 = ddx_d+t4+t7+t12+t18+xhi_x;
t24 = ddy_d+t5+t9+t13+t19+xhi_y;
t22 = 1.0./t21;
t25 = t3.*t22.*t23.*2.920443101711984;
t26 = t2.*t22.*t24.*2.920443101711984;
new_u = [t20-t25+t26;t20+t25-t26];
end
