function q_dot_optimization = q_dot_opt(t,in2,in3,in4)
%Q_DOT_OPT
%    Q_DOT_OPTIMIZATION = Q_DOT_OPT(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:22

b = in4(2,:);
r = in4(1,:);
theta = in2(3,:);
wl = in3(2,:);
wr = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./b;
q_dot_optimization = [(r.*t2.*wl)./2.0+(r.*t2.*wr)./2.0;(r.*t3.*wl)./2.0+(r.*t3.*wr)./2.0;r.*t4.*wl.*(-1.0./2.0)+(r.*t4.*wr)./2.0];
end
