function q_dot = q_dot(t,in2,in3)
%Q_DOT
%    Q_DOT = Q_DOT(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:22

theta = in2(3,:);
wl = in3(2,:);
wr = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
q_dot = [t2.*wl.*4.965e-2+t2.*wr.*4.965e-2;t3.*wl.*4.965e-2+t3.*wr.*4.965e-2;wl.*(-1.712068965517241e-1)+wr.*1.712068965517241e-1];
end
