function q_dot = q_dot(t,in2,in3)
%Q_DOT
%    Q_DOT = Q_DOT(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:09

theta = in2(3,:);
wl = in3(2,:);
wr = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
q_dot = [(t2.*wl)./1.0e+1+(t2.*wr)./1.0e+1;(t3.*wl)./1.0e+1+(t3.*wr)./1.0e+1;wl.*(-1.0./8.0)+wr./8.0];
