function velocities_opt = velocities_opt(in1,in2)
%VELOCITIES_OPT
%    VELOCITIES_OPT = VELOCITIES_OPT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:09

b = in2(2,:);
r = in2(1,:);
wl = in1(2,:);
wr = in1(1,:);
t2 = 1.0./b;
velocities_opt = [(r.*wl)./2.0+(r.*wr)./2.0;r.*t2.*wl.*(-1.0./2.0)+(r.*t2.*wr)./2.0];
