function velocities = velocities(in1)
%VELOCITIES
%    VELOCITIES = VELOCITIES(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Mar-2023 05:30:22

wl = in1(2,:);
wr = in1(1,:);
velocities = [wl.*4.965e-2+wr.*4.965e-2;wl.*(-1.712068965517241e-1)+wr.*1.712068965517241e-1];
end
