function velocities = velocities(in1)
%VELOCITIES
%    VELOCITIES = VELOCITIES(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:09

wl = in1(2,:);
wr = in1(1,:);
velocities = [wl./1.0e+1+wr./1.0e+1;wl.*(-1.0./8.0)+wr./8.0];
