function velocities = velocities(in1,in2)
%VELOCITIES
%    VELOCITIES = VELOCITIES(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 03:31:47

b = in1(2,:);
r = in1(1,:);
wl = in2(2,:);
wr = in2(1,:);
t2 = 1.0./b;
velocities = [(r.*wl)./2.0+(r.*wr)./2.0;r.*t2.*wl.*(-1.0./2.0)+(r.*t2.*wr)./2.0];
end
