function xhi_dot = xhi_dot(t,in2,in3,in4,in5,in6)
%XHI_DOT
%    XHI_DOT = XHI_DOT(T,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Mar-2023 18:49:10

ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
xhi_dot = [t2.*t7.*(ddx_d+dx_d.*2.0-x.*3.0+x_d.*3.0-t2.*xhi_v.*2.0)+t3.*t7.*(ddy_d+dy_d.*2.0-y.*3.0+y_d.*3.0-t3.*xhi_v.*2.0);-x+x_d;-y+y_d];
