function dg_q_xhi_gammaxhi_ = dg_q_xhi_gammaxhi(in1,in2)
%DG_Q_XHI_GAMMAXHI
%    DG_Q_XHI_GAMMAXHI_ = DG_Q_XHI_GAMMAXHI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:40

dg_q_xhi_gammaxhi_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
