function func = dgq_a4y(theta)
%DGQ_A4Y
%    FUNC = DGQ_A4Y(THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:48

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*1.0e+1)./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
