function dh_q_xhi_gammaxhi_ = dh_q_xhi_gammaxhi(in1,in2,in3,in4,in5,in6,in7)
%DH_Q_XHI_GAMMAXHI
%    DH_Q_XHI_GAMMAXHI_ = DH_Q_XHI_GAMMAXHI(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:39

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t8 = 1.0./r;
t9 = x.*1.0e+1;
t10 = x_d.*1.0e+1;
t11 = y.*1.0e+1;
t12 = y_d.*1.0e+1;
t4 = t2.^2;
t5 = t3.^2;
t6 = t2.*xhi_v;
t7 = t3.*xhi_v;
t13 = -t9;
t14 = -t11;
t15 = t4.*xhi_v;
t16 = t5.*xhi_v;
t17 = -t6;
t18 = -t7;
t19 = t4+t5;
t20 = t15+t16;
t22 = ddx_d+dx_d+t10+t13+t17;
t23 = ddy_d+dy_d+t12+t14+t18;
t21 = 1.0./t20.^2;
t24 = t15.*t19.*t21;
t25 = t16.*t19.*t21;
t26 = b.*g1.*t2.*t8.*t19.*t21.*1.0e+1;
t27 = b.*g1.*t3.*t8.*t19.*t21.*1.0e+1;
t28 = t2.*t19.*t21.*t22;
t29 = t3.*t19.*t21.*t23;
t30 = t24+t25+t28+t29;
t31 = b.*g1.*t8.*t30;
dh_q_xhi_gammaxhi_ = reshape([-t27,t27,t26,-t26,t31,-t31],[2,3]);
end
