function g_a_1x_ = g_a_1x(in1,t)
%G_A_1X
%    G_A_1X_ = G_A_1X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:42

theta = in1(3,:);
t2 = cos(theta);
t3 = t.^3;
g_a_1x_ = [(t2.*(t.*6.0+t3.*1.0e+1+t.^2.*3.0))./(sin(theta).^2+t2.^2);t3;0.0];
end
