function g_a_2x_ = g_a_2x(in1,t)
%G_A_2X
%    G_A_2X_ = G_A_2X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:42

theta = in1(3,:);
t2 = cos(theta);
t3 = t.^2;
g_a_2x_ = [(t2.*(t.*2.0+t3.*1.0e+1+2.0))./(sin(theta).^2+t2.^2);t3;0.0];
end
