function h_a_1y_ = h_a_1y(in1,t,in3,in4)
%H_A_1Y
%    H_A_1Y_ = H_A_1Y(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:41

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t9 = 1.0./r;
t7 = t2.^2;
t8 = t3.^2;
t10 = t5.*3.0;
t13 = t6.*1.0e+1;
t11 = t7.*xhi_v;
t12 = t8.*xhi_v;
t15 = t4+t10+t13;
t14 = t11+t12;
t16 = 1.0./t14;
t17 = b.*t2.*t9.*t15.*t16;
h_a_1y_ = [t17;-t17];
end
