function h_a_3x_ = h_a_3x(in1,t,in3,in4)
%H_A_3X
%    H_A_3X_ = H_A_3X(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:41

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t7 = t.*1.0e+1;
t4 = t2.^2;
t5 = t3.^2;
t10 = t7+1.0;
t8 = t4.*xhi_v;
t9 = t5.*xhi_v;
t11 = t8+t9;
t12 = 1.0./t11;
t13 = b.*t3.*t6.*t10.*t12;
h_a_3x_ = [-t13;t13];
end
