function out1 = aaaaaa(t,in2,in3,in4,in5,in6,in7,in8)
%AAAAAA
%    OUT1 = AAAAAA(T,IN2,IN3,IN4,IN5,IN6,IN7,IN8)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Apr-2023 18:35:10

a1x = in4(1);
a2x = in4(2);
a3x = in4(3);
a4x = in4(4);
a1y = in4(5);
a2y = in4(6);
a3y = in4(7);
a4y = in4(8);
b = in5(2,:);
r = in5(1,:);
sens1_1 = in7(1,:);
sens1_2 = in7(2,:);
sens2_1 = in7(3,:);
sens2_2 = in7(4,:);
sens3_1 = in7(5,:);
sens3_2 = in7(6,:);
sensxhi1_1 = in8(1,:);
sensxhi1_2 = in8(2,:);
sensxhi2_1 = in8(3,:);
sensxhi2_2 = in8(4,:);
sensxhi3_1 = in8(5,:);
sensxhi3_2 = in8(6,:);
theta = in2(3,:);
wl = in3(2,:);
wr = in3(1,:);
x = in2(1,:);
xhi_v = in6(1,:);
xhi_x = in6(2,:);
xhi_y = in6(3,:);
y = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = b.^2;
t5 = t.^2;
t6 = t.^3;
t7 = xhi_v.^2;
t8 = 1.0./t7;
et1 = t7.*wl-t7.*wr-a2x.*b.*sensxhi1_1.*t3.*4.0-a3x.*b.*sensxhi1_1.*t3.*6.0-a4x.*b.*sensxhi1_1.*t3.*4.0+a2y.*b.*sensxhi1_1.*t2.*4.0+a3y.*b.*sensxhi1_1.*t2.*6.0+a4y.*b.*sensxhi1_1.*t2.*4.0+b.*sensxhi1_1.*t3.*x.*4.0-b.*sens1_1.*t3.*xhi_v.*4.0+b.*sens2_1.*t2.*xhi_v.*4.0+b.*sensxhi1_1.*t2.*xhi_y.*2.0-b.*sensxhi1_1.*t3.*xhi_x.*2.0+b.*sensxhi2_1.*t3.*xhi_v.*2.0-b.*sensxhi3_1.*t2.*xhi_v.*2.0-b.*sensxhi1_1.*t2.*y.*4.0-a1x.*b.*sensxhi1_1.*t.*t3.*1.2e+1-a2x.*b.*sensxhi1_1.*t.*t3.*1.2e+1-a3x.*b.*sensxhi1_1.*t.*t3.*4.0-a1x.*b.*sensxhi1_1.*t3.*t5.*1.8e+1-a1x.*b.*sensxhi1_1.*t3.*t6.*4.0-a2x.*b.*sensxhi1_1.*t3.*t5.*4.0+a1y.*b.*sensxhi1_1.*t.*t2.*1.2e+1+a2y.*b.*sensxhi1_1.*t.*t2.*1.2e+1+a3y.*b.*sensxhi1_1.*t.*t2.*4.0+a1y.*b.*sensxhi1_1.*t2.*t5.*1.8e+1+a1y.*b.*sensxhi1_1.*t2.*t6.*4.0+a2y.*b.*sensxhi1_1.*t2.*t5.*4.0;
et2 = a2x.*b.*sens3_1.*t2.*xhi_v.*4.0+a3x.*b.*sens3_1.*t2.*xhi_v.*6.0+a4x.*b.*sens3_1.*t2.*xhi_v.*4.0+a2y.*b.*sens3_1.*t3.*xhi_v.*4.0+a3y.*b.*sens3_1.*t3.*xhi_v.*6.0+a4y.*b.*sens3_1.*t3.*xhi_v.*4.0-b.*sens3_1.*t2.*x.*xhi_v.*4.0+b.*sens3_1.*t2.*xhi_v.*xhi_x.*2.0+b.*sens3_1.*t3.*xhi_v.*xhi_y.*2.0-b.*sens3_1.*t3.*xhi_v.*y.*4.0+a1x.*b.*sens3_1.*t.*t2.*xhi_v.*1.2e+1+a2x.*b.*sens3_1.*t.*t2.*xhi_v.*1.2e+1+a3x.*b.*sens3_1.*t.*t2.*xhi_v.*4.0+a1x.*b.*sens3_1.*t2.*t5.*xhi_v.*1.8e+1+a1x.*b.*sens3_1.*t2.*t6.*xhi_v.*4.0+a2x.*b.*sens3_1.*t2.*t5.*xhi_v.*4.0+a1y.*b.*sens3_1.*t.*t3.*xhi_v.*1.2e+1+a2y.*b.*sens3_1.*t.*t3.*xhi_v.*1.2e+1+a3y.*b.*sens3_1.*t.*t3.*xhi_v.*4.0+a1y.*b.*sens3_1.*t3.*t5.*xhi_v.*1.8e+1+a1y.*b.*sens3_1.*t3.*t6.*xhi_v.*4.0+a2y.*b.*sens3_1.*t3.*t5.*xhi_v.*4.0;
et3 = -r.*t7.*wl+r.*t7.*wr-a2x.*sensxhi1_2.*t3.*t4.*4.0-a3x.*sensxhi1_2.*t3.*t4.*6.0-a4x.*sensxhi1_2.*t3.*t4.*4.0+a2y.*sensxhi1_2.*t2.*t4.*4.0+a3y.*sensxhi1_2.*t2.*t4.*6.0+a4y.*sensxhi1_2.*t2.*t4.*4.0+sensxhi1_2.*t3.*t4.*x.*4.0-sens1_2.*t3.*t4.*xhi_v.*4.0+sens2_2.*t2.*t4.*xhi_v.*4.0+sensxhi1_2.*t2.*t4.*xhi_y.*2.0-sensxhi1_2.*t3.*t4.*xhi_x.*2.0+sensxhi2_2.*t3.*t4.*xhi_v.*2.0-sensxhi3_2.*t2.*t4.*xhi_v.*2.0-sensxhi1_2.*t2.*t4.*y.*4.0-a1x.*sensxhi1_2.*t.*t3.*t4.*1.2e+1-a2x.*sensxhi1_2.*t.*t3.*t4.*1.2e+1-a3x.*sensxhi1_2.*t.*t3.*t4.*4.0-a1x.*sensxhi1_2.*t3.*t4.*t5.*1.8e+1-a1x.*sensxhi1_2.*t3.*t4.*t6.*4.0-a2x.*sensxhi1_2.*t3.*t4.*t5.*4.0+a1y.*sensxhi1_2.*t.*t2.*t4.*1.2e+1+a2y.*sensxhi1_2.*t.*t2.*t4.*1.2e+1+a3y.*sensxhi1_2.*t.*t2.*t4.*4.0+a1y.*sensxhi1_2.*t2.*t4.*t5.*1.8e+1+a1y.*sensxhi1_2.*t2.*t4.*t6.*4.0+a2y.*sensxhi1_2.*t2.*t4.*t5.*4.0;
et4 = a2x.*sens3_2.*t2.*t4.*xhi_v.*4.0+a3x.*sens3_2.*t2.*t4.*xhi_v.*6.0+a4x.*sens3_2.*t2.*t4.*xhi_v.*4.0+a2y.*sens3_2.*t3.*t4.*xhi_v.*4.0+a3y.*sens3_2.*t3.*t4.*xhi_v.*6.0+a4y.*sens3_2.*t3.*t4.*xhi_v.*4.0-sens3_2.*t2.*t4.*x.*xhi_v.*4.0+sens3_2.*t2.*t4.*xhi_v.*xhi_x.*2.0+sens3_2.*t3.*t4.*xhi_v.*xhi_y.*2.0-sens3_2.*t3.*t4.*xhi_v.*y.*4.0+a1x.*sens3_2.*t.*t2.*t4.*xhi_v.*1.2e+1+a2x.*sens3_2.*t.*t2.*t4.*xhi_v.*1.2e+1+a3x.*sens3_2.*t.*t2.*t4.*xhi_v.*4.0+a1x.*sens3_2.*t2.*t4.*t5.*xhi_v.*1.8e+1+a1x.*sens3_2.*t2.*t4.*t6.*xhi_v.*4.0+a2x.*sens3_2.*t2.*t4.*t5.*xhi_v.*4.0+a1y.*sens3_2.*t.*t3.*t4.*xhi_v.*1.2e+1+a2y.*sens3_2.*t.*t3.*t4.*xhi_v.*1.2e+1+a3y.*sens3_2.*t.*t3.*t4.*xhi_v.*4.0+a1y.*sens3_2.*t3.*t4.*t5.*xhi_v.*1.8e+1+a1y.*sens3_2.*t3.*t4.*t6.*xhi_v.*4.0+a2y.*sens3_2.*t3.*t4.*t5.*xhi_v.*4.0;
out1 = reshape([sensxhi1_1.*t2+(t2.*wl)./2.0+(t2.*wr)./2.0-(r.*sens3_1.*t3.*wl)./2.0-(r.*sens3_1.*t3.*wr)./2.0,sensxhi1_1.*t3+(t3.*wl)./2.0+(t3.*wr)./2.0+(r.*sens3_1.*t2.*wl)./2.0+(r.*sens3_1.*t2.*wr)./2.0,(t8.*(et1+et2).*(-1.0./2.0))./b,sensxhi1_2.*t2-(r.*sens3_2.*t3.*wl)./2.0-(r.*sens3_2.*t3.*wr)./2.0,sensxhi1_2.*t3+(r.*sens3_2.*t2.*wl)./2.0+(r.*sens3_2.*t2.*wr)./2.0,(t8.*(et3+et4).*(-1.0./2.0))./t4],[3,2]);
end
