function df_p_q_gamma = df_p_q_gamma(g3,theta,wl,wr)
%DF_P_Q_GAMMA
%    DF_P_Q_GAMMA = DF_P_Q_GAMMA(G3,THETA,WL,WR)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 04:14:11

t2 = cos(theta);
t3 = sin(theta);
df_p_q_gamma = reshape([-g3.*((t3.*wl)./2.0+(t3.*wr)./2.0),g3.*((t2.*wl)./2.0+(t2.*wr)./2.0),0.0,0.0,0.0,0.0],[3,2]);
end
