function df_p_u_uai = df_p_u_uai(b,r,theta,u_ai1,u_ai2)
%DF_P_U_UAI
%    DF_P_U_UAI = DF_P_U_UAI(B,R,THETA,U_AI1,U_AI2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 04:14:11

t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./b;
t5 = t4.^2;
df_p_u_uai = reshape([(t2.*u_ai1)./2.0+(t2.*u_ai2)./2.0,(t3.*u_ai1)./2.0+(t3.*u_ai2)./2.0,(t4.*u_ai1)./2.0-(t4.*u_ai2)./2.0,0.0,0.0,r.*t5.*u_ai1.*(-1.0./2.0)+(r.*t5.*u_ai2)./2.0],[3,2]);
end
