function df_q_q_gamma = df_q_q_gamma(g3,r,theta,wl,wr)
%DF_Q_Q_GAMMA
%    DF_Q_Q_GAMMA = DF_Q_Q_GAMMA(G3,R,THETA,WL,WR)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 15:43:01

t2 = cos(theta);
t3 = sin(theta);
df_q_q_gamma = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-g3.*((r.*t2.*wl)./2.0+(r.*t2.*wr)./2.0),-g3.*((r.*t3.*wl)./2.0+(r.*t3.*wr)./2.0),0.0],[3,3]);
end
