function df_u_u_uai = df_u_u_uai
%DF_U_U_UAI
%    DF_U_U_UAI = DF_U_U_UAI

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Apr-2023 15:12:03

df_u_u_uai = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[3,2]);
end
