function df_u_u_uai_ = df_u_u_uai
%DF_U_U_UAI
%    DF_U_U_UAI_ = DF_U_U_UAI

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 17:01:06

df_u_u_uai_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[3,2]);
end
