function df_u_q_gamma = df_u_q_gamma(g3,r,theta)
%DF_U_Q_GAMMA
%    DF_U_Q_GAMMA = DF_U_Q_GAMMA(G3,R,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 04:14:11

t2 = cos(theta);
t3 = sin(theta);
t4 = (g3.*r.*t2)./2.0;
t5 = (g3.*r.*t3)./2.0;
t6 = -t5;
df_u_q_gamma = reshape([t6,t4,0.0,t6,t4,0.0],[3,2]);
end
