function dg_q_q_gamma_ = dg_q_q_gamma(in1,in2,in3,t,in5)
%DG_Q_Q_GAMMA
%    DG_Q_Q_GAMMA_ = DG_Q_Q_GAMMA(IN1,IN2,IN3,T,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 13:02:00

a1x = in5(1);
a2x = in5(2);
a3x = in5(3);
a4x = in5(4);
a5x = in5(5);
a1y = in5(6);
a2y = in5(7);
a3y = in5(8);
a4y = in5(9);
a5y = in5(10);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
theta = in2(3,:);
x = in2(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t5 = t.^3;
t6 = t4.^2;
t7 = t2.^2;
t8 = t3.^2;
t9 = t7+t8;
t10 = 1.0./t9;
dg_q_q_gamma_ = reshape([g3.*t3.*t10.*2.8e+1,0.0,0.0,g3.*t2.*t10.*-2.8e+1,0.0,0.0,-g3.*(t2.*t10.*(a3x.*2.0+a4x.*3.0+a5x.*2.8e+1-x.*2.8e+1+xhi_x.*3.0+a2x.*t.*6.0+a3x.*t.*6.0+a4x.*t.*2.8e+1+a1x.*t4.*1.2e+1+a1x.*t5.*1.2e+1+a2x.*t4.*9.0+a1x.*t6.*2.8e+1+a2x.*t5.*2.8e+1+a3x.*t4.*2.8e+1-t2.*xhi_v.*3.0)+t3.*t10.*(a3y.*2.0+a4y.*3.0+a5y.*2.8e+1+xhi_y.*3.0-y.*2.8e+1+a2y.*t.*6.0+a3y.*t.*6.0+a4y.*t.*2.8e+1+a1y.*t4.*1.2e+1+a1y.*t5.*1.2e+1+a2y.*t4.*9.0+a1y.*t6.*2.8e+1+a2y.*t5.*2.8e+1+a3y.*t4.*2.8e+1-t3.*xhi_v.*3.0)+t7.*t10.*xhi_v.*3.0+t8.*t10.*xhi_v.*3.0)+g1.*t3.*t10.*2.8e+1-g2.*t2.*t10.*2.8e+1,0.0,0.0],[3,3]);
end
