function dg_q_xhi_gammaxhi_ = dg_q_xhi_gammaxhi(in1,in2)
%DG_Q_XHI_GAMMAXHI
%    DG_Q_XHI_GAMMAXHI_ = DG_Q_XHI_GAMMAXHI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 14:46:50

g2 = in1(2,:);
g3 = in1(3,:);
theta = in2(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
dg_q_xhi_gammaxhi_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,g2.*t3.*t7.*-3.0+g3.*t2.*t7.*3.0,0.0,0.0],[3,3]);
end
