function dg_q_xhi_gammaxhi = dg_q_xhi_gammaxhi(in1,in2)
%DG_Q_XHI_GAMMAXHI
%    DG_Q_XHI_GAMMAXHI = DG_Q_XHI_GAMMAXHI(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 18:59:47

g1 = in1(1,:);
g2 = in1(2,:);
theta = in2(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
dg_q_xhi_gammaxhi = reshape([0.0,0.0,0.0,0.0,0.0,0.0,g1.*(t3.*t7.*(t2.*3.0-1.0)-t2.*t3.*t7.*3.0)+g2.*t2.*t7,0.0,0.0],[3,3]);
end
