function dg_q_xhi_gammaxhi = dg_q_xhi_gammaxhi(g2,g3,theta)
%DG_Q_XHI_GAMMAXHI
%    DG_Q_XHI_GAMMAXHI = DG_Q_XHI_GAMMAXHI(G2,G3,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 04:14:12

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
dg_q_xhi_gammaxhi = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-g2.*t3.*t7+g3.*t2.*t7,0.0,0.0],[3,3]);
end
