function dg_q_q_gamma = dg_q_q_gamma(ddx_d,ddy_d,dx_d,dy_d,g1,g2,g3,theta,x,x_d,xhi_v,xhi_x,xhi_y,y,y_d)
%DG_Q_Q_GAMMA
%    DG_Q_Q_GAMMA = DG_Q_Q_GAMMA(DDX_D,DDY_D,DX_D,DY_D,G1,G2,G3,THETA,X,X_D,XHI_V,XHI_X,XHI_Y,Y,Y_D)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 04:14:11

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
dg_q_q_gamma = reshape([g3.*t3.*t7.*2.0,0.0,0.0,g3.*t2.*t7.*-2.0,0.0,0.0,-g3.*(t2.*t7.*(ddx_d+dx_d.*3.0-x.*2.0+x_d.*2.0+xhi_x-t2.*xhi_v.*3.0)+t3.*t7.*(ddy_d+dy_d.*3.0+xhi_y-y.*2.0+y_d.*2.0-t3.*xhi_v.*3.0)+t4.*t7.*xhi_v.*3.0+t5.*t7.*xhi_v.*3.0)+g1.*t3.*t7.*2.0-g2.*t2.*t7.*2.0,0.0,0.0],[3,3]);
end
