function dg_xhi_q_gamma = dg_xhi_q_gamma(in1,in2)
%DG_XHI_Q_GAMMA
%    DG_XHI_Q_GAMMA = DG_XHI_Q_GAMMA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 21:21:36

dg_xhi_q_gamma = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
