function dg_xhi_xhi_gammaxhi = dg_xhi_xhi_gammaxhi
%DG_XHI_XHI_GAMMAXHI
%    DG_XHI_XHI_GAMMAXHI = DG_XHI_XHI_GAMMAXHI

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    01-Apr-2023 14:55:23

dg_xhi_xhi_gammaxhi = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
