function dg_xhi_q_gamma = dg_xhi_q_gamma(g3,theta)
%DG_XHI_Q_GAMMA
%    DG_XHI_Q_GAMMA = DG_XHI_Q_GAMMA(G3,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 04:14:12

t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
dg_xhi_q_gamma = reshape([0.0,0.0,0.0,-g3.*t3.*t7,0.0,0.0,g3.*t2.*t7,0.0,0.0],[3,3]);
end
