function dg_xhi_q_gamma_ = dg_xhi_q_gamma(in1,in2)
%DG_XHI_Q_GAMMA
%    DG_XHI_Q_GAMMA_ = DG_XHI_Q_GAMMA(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    21-Apr-2023 19:03:04

dg_xhi_q_gamma_ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
