function func = dgq_a8x
%DGQ_A8X
%    FUNC = DGQ_A8X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:01

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
