function func = dgq_a7x
%DGQ_A7X
%    FUNC = DGQ_A7X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:00

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
