function func = dgq_a1x(t,theta)
%DGQ_A1X
%    FUNC = DGQ_A1X(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    31-Mar-2023 19:19:55

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.*6.0+t.^2.*9.0+t.^3.*2.0))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
