function func = dgq_a4x(t,theta)
%DGQ_A4X
%    FUNC = DGQ_A4X(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    11-Apr-2023 19:39:52

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.*2.8e+1+3.0))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
