function func = dgq_a2x(t,theta)
%DGQ_A2X
%    FUNC = DGQ_A2X(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 21:21:40

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.*8.0+t.^2.*4.2e+1+2.0))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
