function func = dgq_a3x(t,theta)
%DGQ_A3X
%    FUNC = DGQ_A3X(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 16:10:48

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.*6.0+t.^2.*2.8e+1+2.0))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
