function func = dgq_a2x(t,theta)
%DGQ_A2X
%    FUNC = DGQ_A2X(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 23:10:25

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.*6.0+t.^2.*9.0+t.^3.*2.8e+1))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
