function func = dgq_a1y(t,theta)
%DGQ_A1Y
%    FUNC = DGQ_A1Y(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    21-Apr-2023 19:03:09

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*(t.^2.*1.2e+1+t.^3.*1.6e+1+t.^4.*4.2e+1))./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
