function func = dgq_a1x(t,theta)
%DGQ_A1X
%    FUNC = DGQ_A1X(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 19:14:47

t2 = sin(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,-(t2.*(t.^2.*1.2e+1+t.^3.*1.2e+1+t.^4.*2.8e+1))./(cos(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
