function func = dgq_a15x
%DGQ_A15X
%    FUNC = DGQ_A15X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:03

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
