function func = dgq_a5y(theta)
%DGQ_A5Y
%    FUNC = DGQ_A5Y(THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
<<<<<<< HEAD
%    13-Apr-2023 01:17:14
=======
%    12-Apr-2023 23:01:06
>>>>>>> 4600c42c8e268931e4ea11d53d8f97c1fb4bcee2

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*2.8e+1)./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
