function func = dgq_a6y
%DGQ_A6Y
%    FUNC = DGQ_A6Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:04

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
