function func = dgq_a5y(theta)
%DGQ_A5Y
%    FUNC = DGQ_A5Y(THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 21:10:24

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*4.2e+1)./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
