function func = dgq_a4x
%DGQ_A4X
%    FUNC = DGQ_A4X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 01:55:40

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
