function func = dgq_a4y(t,theta)
%DGQ_A4Y
%    FUNC = DGQ_A4Y(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    16-Apr-2023 20:17:39

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*(t.*2.8e+1+3.0))./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
