function func = dgq_a2y(t,theta)
%DGQ_A2Y
%    FUNC = DGQ_A2Y(T,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-Apr-2023 17:40:45

t2 = cos(theta);
func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,(t2.*(t.*6.0+t.^2.*1.2e+1+t.^3.*4.2e+1))./(sin(theta).^2+t2.^2),0.0,0.0],[3,3]);
end
