function func = dgq_a8y
%DGQ_A8Y
%    FUNC = DGQ_A8Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:05

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
