function func = dgq_a2x
%DGQ_A2X
%    FUNC = DGQ_A2X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 01:55:40

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
