function func = dgxhi_a14x
%DGXHI_A14X
%    FUNC = DGXHI_A14X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:11

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
