function func = dgxhi_a10x
%DGXHI_A10X
%    FUNC = DGXHI_A10X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:09

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
