function func = dgxhi_a4x
%DGXHI_A4X
%    FUNC = DGXHI_A4X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-May-2023 15:20:29

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
