function func = dgxhi_a4x
%DGXHI_A4X
%    FUNC = DGXHI_A4X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 02:13:22

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
