function func = dgxhi_a9y
%DGXHI_A9Y
%    FUNC = DGXHI_A9Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:13

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
