function func = dgxhi_a3x
%DGXHI_A3X
%    FUNC = DGXHI_A3X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Apr-2023 18:38:38

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
