function func = dgxhi_a12y
%DGXHI_A12Y
%    FUNC = DGXHI_A12Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:14

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
