function func = dgxhi_a15y
%DGXHI_A15Y
%    FUNC = DGXHI_A15Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:15

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
