function func = dgxhi_a5x
%DGXHI_A5X
%    FUNC = DGXHI_A5X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    16-Apr-2023 20:17:39

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
