function func = dgxhi_a2x
%DGXHI_A2X
%    FUNC = DGXHI_A2X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Apr-2023 16:11:25

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
