function func = dgxhi_a14y
%DGXHI_A14Y
%    FUNC = DGXHI_A14Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:15

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
