function func = dgxhi_a5y
%DGXHI_A5Y
%    FUNC = DGXHI_A5Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 17:01:15

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
