function func = dgxhi_a3y
%DGXHI_A3Y
%    FUNC = DGXHI_A3Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 18:59:50

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
