function func = dgxhi_a8y
%DGXHI_A8Y
%    FUNC = DGXHI_A8Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:45:13

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
