function dh_q_xhi_gammaxhi = dh_q_xhi_gammaxhi(in1,in2,in3,in4,in5,in6,in7)
%DH_Q_XHI_GAMMAXHI
%    DH_Q_XHI_GAMMAXHI = DH_Q_XHI_GAMMAXHI(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 18:59:46

b = in1(2,:);
ddx_d = in7(1,:);
ddy_d = in7(2,:);
dx_d = in6(1,:);
dy_d = in6(2,:);
g1 = in2(1,:);
g2 = in2(2,:);
r = in1(1,:);
theta = in3(3,:);
x = in3(1,:);
x_d = in5(1,:);
xhi_v = in4(1,:);
xhi_x = in4(2,:);
y = in3(2,:);
y_d = in5(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t13 = 1.0./r;
t10 = t2.*3.0;
t11 = t2.^2;
t12 = t3.^2;
t14 = -t6;
t15 = -t8;
t17 = t3.*xhi_v.*3.0;
t20 = t2.*xhi_v.*-3.0;
t16 = t10.*xhi_v;
t18 = t11.*xhi_v;
t19 = t12.*xhi_v;
t21 = -t17;
t22 = t10-1.0;
t23 = t11+t12;
t27 = ddx_d+t4+t7+t14+t20+xhi_v;
t24 = t18+t19;
t28 = ddy_d+t5+t9+t15+t21+xhi_x;
t25 = 1.0./t24;
t26 = t25.^2;
t30 = t11.*t25.*-3.0;
t31 = b.*g2.*t3.*t13.*t25;
t32 = t2.*t22.*t25;
t33 = t2.*t16.*t23.*t26;
t34 = t19.*t23.*t26.*3.0;
t35 = b.*g1.*t2.*t13.*t23.*t26.*2.0;
t36 = b.*g1.*t3.*t13.*t23.*t26.*2.0;
t37 = t2.*t23.*t26.*t27;
t38 = t3.*t23.*t26.*t28;
t39 = t30+t32+t33+t34+t37+t38;
t40 = b.*g1.*t13.*t39;
dh_q_xhi_gammaxhi = reshape([-t36,t36,t35,-t35,-t31+t40,t31-t40],[2,3]);
end
