function dh_q_q_gamma_ = dh_q_q_gamma(in1,in2,in3,in4,in5,in6,in7)
%DH_Q_Q_GAMMA
%    DH_Q_Q_GAMMA_ = DH_Q_Q_GAMMA(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-Apr-2023 17:40:35

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*4.0;
t5 = dy_d.*4.0;
t8 = 1.0./r;
t9 = x.*4.2e+1;
t10 = x_d.*4.2e+1;
t11 = y.*4.2e+1;
t12 = y_d.*4.2e+1;
t6 = t2.^2;
t7 = t3.^2;
t13 = t2.*xhi_v.*4.0;
t14 = t3.*xhi_v.*4.0;
t15 = -t9;
t16 = -t11;
t17 = t6.*xhi_v;
t18 = t7.*xhi_v;
t19 = -t13;
t20 = -t14;
t21 = t17+t18;
t23 = ddx_d+t4+t10+t15+t19;
t24 = ddy_d+t5+t12+t16+t20;
t22 = 1.0./t21;
t25 = b.*g1.*t2.*t8.*t22.*4.2e+1;
t26 = b.*g3.*t2.*t8.*t22.*4.2e+1;
t27 = b.*g2.*t3.*t8.*t22.*4.2e+1;
t28 = b.*g3.*t3.*t8.*t22.*4.2e+1;
t29 = t3.*t22.*t23;
t30 = t2.*t22.*t24;
t31 = -t30;
t32 = t29+t31;
t33 = b.*g3.*t8.*t32;
dh_q_q_gamma_ = reshape([t26,-t26,t28,-t28,t25+t27+t33,-t25-t27-t33],[2,3]);
end
