function dh_q_xhi_gammaxhi_ = dh_q_xhi_gammaxhi(in1,in2,in3,in4,in5,in6,in7)
%DH_Q_XHI_GAMMAXHI
%    DH_Q_XHI_GAMMAXHI_ = DH_Q_XHI_GAMMAXHI(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 17:01:07

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*4.0;
t5 = dy_d.*4.0;
t8 = 1.0./r;
t9 = x.*4.2e+1;
t10 = x_d.*4.2e+1;
t11 = y.*4.2e+1;
t12 = y_d.*4.2e+1;
t6 = t2.^2;
t7 = t3.^2;
t13 = t2.*xhi_v.*4.0;
t14 = t3.*xhi_v.*4.0;
t15 = -t9;
t16 = -t11;
t17 = t6.*xhi_v;
t18 = t7.*xhi_v;
t19 = -t13;
t20 = -t14;
t21 = t6+t7;
t22 = t17+t18;
t24 = ddx_d+t4+t10+t15+t19;
t25 = ddy_d+t5+t12+t16+t20;
t23 = 1.0./t22.^2;
t26 = t17.*t21.*t23.*4.0;
t27 = t18.*t21.*t23.*4.0;
t28 = b.*g1.*t2.*t8.*t21.*t23.*4.2e+1;
t29 = b.*g1.*t3.*t8.*t21.*t23.*4.2e+1;
t30 = t3.*t21.*t23.*t25;
t31 = t2.*t21.*t23.*t24;
t32 = t26+t27+t30+t31;
t33 = b.*g1.*t8.*t32;
dh_q_xhi_gammaxhi_ = reshape([-t29,t29,t28,-t28,t33,-t33],[2,3]);
end
