function dh_q_q_gamma_ = dh_q_q_gamma(in1,in2,in3,in4,in5,in6,in7)
%DH_Q_Q_GAMMA
%    DH_Q_Q_GAMMA_ = DH_Q_Q_GAMMA(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Apr-2023 16:01:11

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = xhi_x.*3.0;
t7 = xhi_y.*3.0;
t10 = 1.0./r;
t11 = x.*2.8e+1;
t12 = x_d.*2.8e+1;
t13 = y.*2.8e+1;
t14 = y_d.*2.8e+1;
t8 = t2.^2;
t9 = t3.^2;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = -t11;
t18 = -t13;
t19 = t8.*xhi_v;
t20 = t9.*xhi_v;
t21 = -t15;
t22 = -t16;
t23 = t19+t20;
t25 = ddx_d+t4+t6+t12+t17+t21;
t26 = ddy_d+t5+t7+t14+t18+t22;
t24 = 1.0./t23;
t27 = b.*g1.*t2.*t10.*t24.*2.8e+1;
t28 = b.*g3.*t2.*t10.*t24.*2.8e+1;
t29 = b.*g2.*t3.*t10.*t24.*2.8e+1;
t30 = b.*g3.*t3.*t10.*t24.*2.8e+1;
t31 = t3.*t24.*t25;
t32 = t2.*t24.*t26;
t33 = -t32;
t34 = t31+t33;
t35 = b.*g3.*t10.*t34;
dh_q_q_gamma_ = reshape([t28,-t28,t30,-t30,t27+t29+t35,-t27-t29-t35],[2,3]);
end
