function dh_q_q_gamma = dh_q_q_gamma(b,ddx_d,ddy_d,dx_d,dy_d,g1,g2,g3,r,theta,x,x_d,xhi_v,xhi_x,xhi_y,y,y_d)
%DH_Q_Q_GAMMA
%    DH_Q_Q_GAMMA = DH_Q_Q_GAMMA(B,DDX_D,DDY_D,DX_D,DY_D,G1,G2,G3,R,THETA,X,X_D,XHI_V,XHI_X,XHI_Y,Y,Y_D)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 15:43:01

t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t12 = 1.0./r;
t10 = t2.^2;
t11 = t3.^2;
t13 = -t6;
t14 = -t8;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = t10.*xhi_v;
t18 = t11.*xhi_v;
t19 = -t15;
t20 = -t16;
t21 = t17+t18;
t23 = ddx_d+t4+t7+t13+t19+xhi_x;
t24 = ddy_d+t5+t9+t14+t20+xhi_y;
t22 = 1.0./t21;
t25 = b.*g1.*t2.*t12.*t22.*2.0;
t26 = b.*g3.*t2.*t12.*t22.*2.0;
t27 = b.*g2.*t3.*t12.*t22.*2.0;
t28 = b.*g3.*t3.*t12.*t22.*2.0;
t29 = t3.*t22.*t23;
t30 = t2.*t22.*t24;
t31 = -t30;
t32 = t29+t31;
t33 = b.*g3.*t12.*t32;
dh_q_q_gamma = reshape([t26,-t26,t28,-t28,t25+t27+t33,-t25-t27-t33],[2,3]);
end
