function dh_q_xhi_gammaxhi_ = dh_q_xhi_gammaxhi(in1,in2,in3,in4,in5,in6,in7)
%DH_Q_XHI_GAMMAXHI
%    DH_Q_XHI_GAMMAXHI_ = DH_Q_XHI_GAMMAXHI(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 14:46:49

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = xhi_x.*3.0;
t7 = xhi_y.*3.0;
t10 = 1.0./r;
t11 = x.*2.8e+1;
t12 = x_d.*2.8e+1;
t13 = y.*2.8e+1;
t14 = y_d.*2.8e+1;
t8 = t2.^2;
t9 = t3.^2;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = -t11;
t18 = -t13;
t19 = t8.*xhi_v;
t20 = t9.*xhi_v;
t21 = -t15;
t22 = -t16;
t23 = t8+t9;
t24 = t19+t20;
t27 = ddx_d+t4+t6+t12+t17+t21;
t28 = ddy_d+t5+t7+t14+t18+t22;
t25 = 1.0./t24;
t26 = t25.^2;
t29 = b.*g2.*t2.*t10.*t25.*3.0;
t30 = b.*g3.*t3.*t10.*t25.*3.0;
t31 = t19.*t23.*t26.*3.0;
t32 = t20.*t23.*t26.*3.0;
t33 = b.*g1.*t2.*t10.*t23.*t26.*2.8e+1;
t34 = b.*g1.*t3.*t10.*t23.*t26.*2.8e+1;
t35 = t2.*t23.*t26.*t27;
t36 = t3.*t23.*t26.*t28;
t37 = t31+t32+t35+t36;
t38 = b.*g1.*t10.*t37;
dh_q_xhi_gammaxhi_ = reshape([-t34,t34,t33,-t33,-t29-t30+t38,t29+t30-t38],[2,3]);
end
