function dh_xhi_xhi_gammaxhi_ = dh_xhi_xhi_gammaxhi(in1,in2,in3,in4,in5,in6,in7)
%DH_XHI_XHI_GAMMAXHI
%    DH_XHI_XHI_GAMMAXHI_ = DH_XHI_XHI_GAMMAXHI(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 16:10:43

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = xhi_x.*3.0;
t7 = xhi_y.*3.0;
t10 = 1.0./r;
t11 = x.*2.8e+1;
t12 = x_d.*2.8e+1;
t13 = y.*2.8e+1;
t14 = y_d.*2.8e+1;
t8 = t2.^2;
t9 = t3.^2;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = -t11;
t18 = -t13;
t19 = t8.*xhi_v;
t20 = t9.*xhi_v;
t21 = -t15;
t22 = -t16;
t23 = t8+t9;
t24 = t23.^2;
t25 = t19+t20;
t28 = ddx_d+t4+t6+t12+t17+t21;
t29 = ddy_d+t5+t7+t14+t18+t22;
t26 = 1.0./t25.^2;
t27 = 1.0./t25.^3;
t30 = b.*g1.*t2.*t10.*t23.*t26.*3.0;
t31 = b.*g3.*t2.*t10.*t23.*t26.*3.0;
t32 = b.*g1.*t3.*t10.*t23.*t26.*3.0;
t33 = b.*g2.*t3.*t10.*t23.*t26.*3.0;
t34 = t3.*t24.*t27.*t28.*2.0;
t35 = t2.*t24.*t27.*t29.*2.0;
t36 = -t35;
t37 = t34+t36;
t38 = b.*g1.*t10.*t37;
dh_xhi_xhi_gammaxhi_ = reshape([-t31+t33-t38,t31-t33+t38,t32,-t32,-t30,t30],[2,3]);
end
