function dh_xhi_xhi_gammaxhi = dh_xhi_xhi_gammaxhi(in1,in2,in3,in4,in5,in6,in7)
%DH_XHI_XHI_GAMMAXHI
%    DH_XHI_XHI_GAMMAXHI = DH_XHI_XHI_GAMMAXHI(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 12:38:14

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t12 = 1.0./r;
t10 = t2.^2;
t11 = t3.^2;
t13 = -t6;
t14 = -t8;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = t10.*xhi_v;
t18 = t11.*xhi_v;
t19 = -t15;
t20 = -t16;
t21 = t10+t11;
t22 = t21.^2;
t23 = t17+t18;
t26 = ddx_d+t4+t7+t13+t19+xhi_x;
t27 = ddy_d+t5+t9+t14+t20+xhi_y;
t24 = 1.0./t23.^2;
t25 = 1.0./t23.^3;
t28 = b.*g1.*t2.*t12.*t21.*t24;
t29 = b.*g3.*t2.*t12.*t21.*t24;
t30 = b.*g1.*t3.*t12.*t21.*t24;
t31 = b.*g2.*t3.*t12.*t21.*t24;
t32 = t3.*t22.*t25.*t26.*2.0;
t33 = t2.*t22.*t25.*t27.*2.0;
t34 = -t33;
t35 = t32+t34;
t36 = b.*g1.*t12.*t35;
dh_xhi_xhi_gammaxhi = reshape([-t29+t31-t36,t29-t31+t36,t30,-t30,-t28,t28],[2,3]);
end
