function dh_xhi_xhi_gammaxhi_ = dh_xhi_xhi_gammaxhi(in1,in2,in3,in4,in5,in6,in7)
%DH_XHI_XHI_GAMMAXHI
%    DH_XHI_XHI_GAMMAXHI_ = DH_XHI_XHI_GAMMAXHI(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:40

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t8 = 1.0./r;
t9 = x.*1.0e+1;
t10 = x_d.*1.0e+1;
t11 = y.*1.0e+1;
t12 = y_d.*1.0e+1;
t4 = t2.^2;
t5 = t3.^2;
t6 = t2.*xhi_v;
t7 = t3.*xhi_v;
t13 = -t9;
t14 = -t11;
t15 = t4.*xhi_v;
t16 = t5.*xhi_v;
t17 = -t6;
t18 = -t7;
t19 = t4+t5;
t20 = t19.^2;
t21 = t15+t16;
t23 = ddx_d+dx_d+t10+t13+t17;
t24 = ddy_d+dy_d+t12+t14+t18;
t22 = 1.0./t21.^3;
t25 = t3.*t20.*t22.*t23.*2.0;
t26 = t2.*t20.*t22.*t24.*2.0;
t27 = -t26;
t28 = t25+t27;
t29 = b.*g1.*t8.*t28;
dh_xhi_xhi_gammaxhi_ = reshape([-t29,t29,0.0,0.0,0.0,0.0],[2,3]);
end
