function dh_xhi_q_gamma = dh_xhi_q_gamma(in1,in2,in3,in4,in5,in6,in7)
%DH_XHI_Q_GAMMA
%    DH_XHI_Q_GAMMA = DH_XHI_Q_GAMMA(IN1,IN2,IN3,IN4,IN5,IN6,IN7)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Mar-2023 00:24:48

b = in7(2,:);
ddx_d = in6(1,:);
ddy_d = in6(2,:);
dx_d = in5(1,:);
dy_d = in5(2,:);
g1 = in1(1,:);
g2 = in1(2,:);
g3 = in1(3,:);
r = in7(1,:);
theta = in2(3,:);
x = in2(1,:);
x_d = in4(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
y_d = in4(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t12 = 1.0./r;
t10 = t2.^2;
t11 = t3.^2;
t13 = -t6;
t14 = -t8;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = t10.*xhi_v;
t18 = t11.*xhi_v;
t19 = -t15;
t20 = -t16;
t21 = t10+t11;
t22 = t17+t18;
t25 = ddx_d+t4+t7+t13+t19+xhi_x;
t26 = ddy_d+t5+t9+t14+t20+xhi_y;
t23 = 1.0./t22;
t24 = t23.^2;
t27 = b.*g3.*t2.*t12.*t23;
t28 = b.*g3.*t3.*t12.*t23;
t29 = t17.*t21.*t24.*3.0;
t30 = t18.*t21.*t24.*3.0;
t31 = b.*g2.*t2.*t12.*t21.*t24.*2.0;
t32 = b.*g1.*t3.*t12.*t21.*t24.*2.0;
t33 = t2.*t21.*t24.*t25;
t34 = t3.*t21.*t24.*t26;
t35 = t29+t30+t33+t34;
t36 = b.*g3.*t12.*t35;
dh_xhi_q_gamma = reshape([t31-t32+t36,-t31+t32-t36,-t27,t27,-t28,t28],[2,3]);
end
