function func = dhq_a13x
%DHQ_A13X
%    FUNC = DHQ_A13X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:44

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
