function func = dhq_a2y
%DHQ_A2Y
%    FUNC = DHQ_A2Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 18:59:48

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
