function func = dhq_a3y
%DHQ_A3Y
%    FUNC = DHQ_A3Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:38

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
