function func = dhq_a3x
%DHQ_A3X
%    FUNC = DHQ_A3X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:38

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
