function func = dhq_a8y
%DHQ_A8Y
%    FUNC = DHQ_A8Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:48

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
