function func = dhq_a8x
%DHQ_A8X
%    FUNC = DHQ_A8X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:43

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
