function func = dhq_a1x
%DHQ_A1X
%    FUNC = DHQ_A1X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:37

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
