function func = dhq_a2x
%DHQ_A2X
%    FUNC = DHQ_A2X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 01:55:38

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
