function func = dhq_a6x
%DHQ_A6X
%    FUNC = DHQ_A6X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:42

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
