function func = dhq_a3y(b,r,t,theta,xhi_v)
%DHQ_A3Y
%    FUNC = DHQ_A3Y(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 01:17:04

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t8 = 1.0./r;
t6 = t2.^2;
t7 = t3.^2;
t11 = t5.*2.8e+1;
t9 = t6.*xhi_v;
t10 = t7.*xhi_v;
t12 = t4+t11+2.0;
t13 = t9+t10;
t14 = 1.0./t13;
t15 = b.*t3.*t8.*t12.*t14;
func = reshape([0.0,0.0,0.0,0.0,-t15,t15],[2,3]);
end
