function func = dhq_a11x
%DHQ_A11X
%    FUNC = DHQ_A11X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:44

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
