function func = dhq_a11y
%DHQ_A11Y
%    FUNC = DHQ_A11Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:48

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
