function func = dhq_a7x
%DHQ_A7X
%    FUNC = DHQ_A7X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:42

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
