function func = dhq_a4x(b,r,theta,xhi_v)
%DHQ_A4X
%    FUNC = DHQ_A4X(B,R,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    31-Mar-2023 19:19:53

t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t4 = t2.^2;
t5 = t3.^2;
t7 = t4.*xhi_v;
t8 = t5.*xhi_v;
t9 = t7+t8;
t10 = 1.0./t9;
t11 = b.*t2.*t6.*t10.*2.0;
func = reshape([0.0,0.0,0.0,0.0,-t11,t11],[2,3]);
end
