function func = dhq_a2x(b,r,t,theta,xhi_v)
%DHQ_A2X
%    FUNC = DHQ_A2X(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
<<<<<<< HEAD
%    30-Mar-2023 16:42:09
=======
%    30-Mar-2023 19:08:56
>>>>>>> anto

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t8 = 1.0./r;
t6 = t2.^2;
t7 = t3.^2;
t9 = t5.*2.0;
t10 = t6.*xhi_v;
t11 = t7.*xhi_v;
t12 = t4+t9+2.0;
t13 = t10+t11;
t14 = 1.0./t13;
t15 = b.*t2.*t8.*t12.*t14;
func = reshape([0.0,0.0,0.0,0.0,-t15,t15],[2,3]);
end
