function func = dhq_a4x(b,r,t,theta,xhi_v)
%DHQ_A4X
%    FUNC = DHQ_A4X(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-Apr-2023 17:40:40

t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t7 = t.*4.2e+1;
t4 = t2.^2;
t5 = t3.^2;
t10 = t7+4.0;
t8 = t4.*xhi_v;
t9 = t5.*xhi_v;
t11 = t8+t9;
t12 = 1.0./t11;
t13 = b.*t2.*t6.*t10.*t12;
func = reshape([0.0,0.0,0.0,0.0,-t13,t13],[2,3]);
end
