function func = dhq_a7y
%DHQ_A7Y
%    FUNC = DHQ_A7Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:47

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
