function func = dhq_a12y
%DHQ_A12Y
%    FUNC = DHQ_A12Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:49

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
