function func = dhxhi_a12y
%DHXHI_A12Y
%    FUNC = DHXHI_A12Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:58

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
