function func = dhxhi_a3x(b,r,t,theta,xhi_v)
%DHXHI_A3X
%    FUNC = DHXHI_A3X(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    21-Apr-2023 19:03:07

t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t7 = 1.0./r;
t8 = t.*8.0;
t5 = t2.^2;
t6 = t3.^2;
t11 = t4.*4.2e+1;
t9 = t5.*xhi_v;
t10 = t6.*xhi_v;
t12 = t5+t6;
t13 = t8+t11+2.0;
t14 = t9+t10;
t15 = 1.0./t14.^2;
t16 = b.*t3.*t7.*t12.*t13.*t15;
func = reshape([t16,-t16,0.0,0.0,0.0,0.0],[2,3]);
end
