function func = dhxhi_a15y
%DHXHI_A15Y
%    FUNC = DHXHI_A15Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:59

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
