function func = dhxhi_a4x
%DHXHI_A4X
%    FUNC = DHXHI_A4X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:38

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
