function func = dhxhi_a15x
%DHXHI_A15X
%    FUNC = DHXHI_A15X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:55

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
