function func = dhxhi_a12x
%DHXHI_A12X
%    FUNC = DHXHI_A12X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:54

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
