function func = dhxhi_a2y(b,r,t,theta,xhi_v)
%DHXHI_A2Y
%    FUNC = DHXHI_A2Y(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    21-Apr-2023 19:03:08

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t9 = 1.0./r;
t7 = t2.^2;
t8 = t3.^2;
t12 = t5.*1.2e+1;
t13 = t6.*4.2e+1;
t10 = t7.*xhi_v;
t11 = t8.*xhi_v;
t14 = t7+t8;
t16 = t4+t12+t13;
t15 = t10+t11;
t17 = 1.0./t15.^2;
t18 = b.*t2.*t9.*t14.*t16.*t17;
func = reshape([-t18,t18,0.0,0.0,0.0,0.0],[2,3]);
end
