function func = dhxhi_a7x
%DHXHI_A7X
%    FUNC = DHXHI_A7X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:52

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
