function func = dhxhi_a1y
%DHXHI_A1Y
%    FUNC = DHXHI_A1Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:38

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
