function func = dhxhi_a1x(b,r,t,theta,xhi_v)
%DHXHI_A1X
%    FUNC = DHXHI_A1X(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
<<<<<<< HEAD
%    13-Apr-2023 01:17:05
=======
%    12-Apr-2023 23:01:04
>>>>>>> 4600c42c8e268931e4ea11d53d8f97c1fb4bcee2

t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t5 = t.^3;
t9 = 1.0./r;
t6 = t4.^2;
t7 = t2.^2;
t8 = t3.^2;
t12 = t4.*1.2e+1;
t13 = t5.*1.2e+1;
t10 = t7.*xhi_v;
t11 = t8.*xhi_v;
t14 = t6.*2.8e+1;
t15 = t7+t8;
t16 = t10+t11;
t18 = t12+t13+t14;
t17 = 1.0./t16.^2;
t19 = b.*t3.*t9.*t15.*t17.*t18;
func = reshape([t19,-t19,0.0,0.0,0.0,0.0],[2,3]);
end
