function func = dhxhi_a13y
%DHXHI_A13Y
%    FUNC = DHXHI_A13Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:58

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
