function func = dhxhi_a4y(b,r,theta,xhi_v)
%DHXHI_A4Y
%    FUNC = DHXHI_A4Y(B,R,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 21:21:40

t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t4 = t2.^2;
t5 = t3.^2;
t7 = t4.*xhi_v;
t8 = t5.*xhi_v;
t9 = t4+t5;
t10 = t7+t8;
t11 = 1.0./t10.^2;
t12 = b.*t2.*t6.*t9.*t11.*4.2e+1;
func = reshape([-t12,t12,0.0,0.0,0.0,0.0],[2,3]);
end
