function func = dhxhi_a3y
%DHXHI_A3Y
%    FUNC = DHXHI_A3Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 01:55:39

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
