function func = dhxhi_a3x(b,r,t,theta,xhi_v)
%DHXHI_A3X
%    FUNC = DHXHI_A3X(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 23:10:22

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t8 = 1.0./r;
t6 = t2.^2;
t7 = t3.^2;
t11 = t5.*2.8e+1;
t9 = t6.*xhi_v;
t10 = t7.*xhi_v;
t12 = t6+t7;
t13 = t4+t11+2.0;
t14 = t9+t10;
t15 = 1.0./t14.^2;
t16 = b.*t3.*t8.*t12.*t13.*t15;
func = reshape([t16,-t16,0.0,0.0,0.0,0.0],[2,3]);
end
