function func = dhxhi_a8x
%DHXHI_A8X
%    FUNC = DHXHI_A8X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:53

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
