function func = dhxhi_a3y(b,r,t,theta,xhi_v)
%DHXHI_A3Y
%    FUNC = DHXHI_A3Y(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Mar-2023 16:42:13

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*2.0;
t7 = 1.0./r;
t5 = t2.^2;
t6 = t3.^2;
t8 = t4+3.0;
t9 = t5.*xhi_v;
t10 = t6.*xhi_v;
t11 = t5+t6;
t12 = t9+t10;
t13 = 1.0./t12.^2;
t14 = b.*t2.*t7.*t8.*t11.*t13;
func = reshape([-t14,t14,0.0,0.0,0.0,0.0],[2,3]);
end
