function func = dhxhi_a1x
%DHXHI_A1X
%    FUNC = DHXHI_A1X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 18:59:48

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
