function func = dhxhi_a3y(b,r,t,theta,xhi_v)
%DHXHI_A3Y
%    FUNC = DHXHI_A3Y(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
<<<<<<< HEAD
%    13-Apr-2023 01:17:09
=======
%    12-Apr-2023 23:01:05
>>>>>>> 4600c42c8e268931e4ea11d53d8f97c1fb4bcee2

t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t8 = 1.0./r;
t6 = t2.^2;
t7 = t3.^2;
t11 = t5.*2.8e+1;
t9 = t6.*xhi_v;
t10 = t7.*xhi_v;
t12 = t6+t7;
t13 = t4+t11+2.0;
t14 = t9+t10;
t15 = 1.0./t14.^2;
t16 = b.*t2.*t8.*t12.*t13.*t15;
func = reshape([-t16,t16,0.0,0.0,0.0,0.0],[2,3]);
end
