function func = dhxhi_a4y
%DHXHI_A4Y
%    FUNC = DHXHI_A4Y

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 01:55:39

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
