function func = dhxhi_a4x(b,r,t,theta,xhi_v)
%DHXHI_A4X
%    FUNC = DHXHI_A4X(B,R,T,THETA,XHI_V)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-Apr-2023 17:40:42

t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t7 = t.*4.2e+1;
t4 = t2.^2;
t5 = t3.^2;
t10 = t7+4.0;
t8 = t4.*xhi_v;
t9 = t5.*xhi_v;
t11 = t4+t5;
t12 = t8+t9;
t13 = 1.0./t12.^2;
t14 = b.*t3.*t6.*t10.*t11.*t13;
func = reshape([t14,-t14,0.0,0.0,0.0,0.0],[2,3]);
end
