function func = dhxhi_a10x
%DHXHI_A10X
%    FUNC = DHXHI_A10X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:53

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
