function func = dhxhi_a11x
%DHXHI_A11X
%    FUNC = DHXHI_A11X

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:54

func = reshape([0.0,0.0,0.0,0.0,0.0,0.0],[2,3]);
end
