function f_p = ff_p(b,r,theta,wl,wr)
%FF_P
%    F_P = FF_P(B,R,THETA,WL,WR)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 15:43:00

t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./b;
t5 = t4.^2;
f_p = reshape([(t2.*wl)./2.0+(t2.*wr)./2.0,(t3.*wl)./2.0+(t3.*wr)./2.0,t4.*wl.*(-1.0./2.0)+(t4.*wr)./2.0,0.0,0.0,(r.*t5.*wl)./2.0-(r.*t5.*wr)./2.0],[3,2]);
end
