function f_q = ff_q(r,theta,wl,wr)
%FF_Q
%    F_Q = FF_Q(R,THETA,WL,WR)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 15:43:00

t2 = cos(theta);
t3 = sin(theta);
f_q = reshape([0.0,0.0,0.0,0.0,0.0,0.0,r.*t3.*wl.*(-1.0./2.0)-(r.*t3.*wr)./2.0,(r.*t2.*wl)./2.0+(r.*t2.*wr)./2.0,0.0],[3,3]);
end
