function f_q = ff_q(in1,in2,in3)
%FF_Q
%    F_Q = FF_Q(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
<<<<<<< HEAD
%    13-Apr-2023 01:16:49
=======
%    12-Apr-2023 23:00:59
>>>>>>> 4600c42c8e268931e4ea11d53d8f97c1fb4bcee2

r = in3(1,:);
theta = in1(3,:);
wl = in2(2,:);
wr = in2(1,:);
t2 = cos(theta);
t3 = sin(theta);
f_q = reshape([0.0,0.0,0.0,0.0,0.0,0.0,r.*t3.*wl.*(-1.0./2.0)-(r.*t3.*wr)./2.0,(r.*t2.*wl)./2.0+(r.*t2.*wr)./2.0,0.0],[3,3]);
end
