function f_u = ff_u(b,r,theta)
%FF_U
%    F_U = FF_U(B,R,THETA)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 04:14:10

t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./b;
t5 = (r.*t2)./2.0;
t6 = (r.*t3)./2.0;
t7 = (r.*t4)./2.0;
f_u = reshape([t5,t6,t7,t5,t6,-t7],[3,2]);
end
