function g_q = fg_q(in1,in2,in3,in4,in5)
%FG_Q
%    G_Q = FG_Q(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Apr-2023 19:22:20

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = conj(theta);
t3 = cos(theta);
t4 = conj(xhi_v);
t5 = sin(theta);
t6 = cos(t2);
t7 = sin(t2);
t8 = t3.^2;
t9 = t5.^2;
t10 = t6.^2;
t11 = t7.^2;
t12 = t3.*t6;
t13 = t5.*t6;
t14 = t3.*t7;
t15 = t5.*t7;
t16 = -t15;
t17 = t4.*t12.*xhi_v;
t18 = t4.*t13.*xhi_v;
t19 = t4.*t14.*xhi_v;
t20 = t4.*t15.*xhi_v;
t24 = t4.*t8.*t10.*xhi_v;
t25 = t4.*t9.*t10.*xhi_v;
t26 = t4.*t8.*t11.*xhi_v;
t27 = t4.*t9.*t11.*xhi_v;
t21 = -t17;
t22 = -t18;
t23 = -t19;
t28 = t12+t20;
t29 = t15+t17;
t34 = t24+t25+t26+t27;
t30 = t13+t23;
t31 = t14+t22;
t32 = t16+t21+t28;
t35 = 1.0./t34;
t33 = t30+t31;
g_q = reshape([t6.*t29.*t35.*-2.8e+1+t7.*t30.*t35.*2.8e+1,-1.0,0.0,t7.*t28.*t35.*-2.8e+1+t6.*t31.*t35.*2.8e+1,0.0,-1.0,-(t6.*t30.*t35+t7.*t29.*t35-t6.*t33.*t35+t7.*t32.*t35).*(ddx_d+dx_d.*3.0-x.*2.8e+1+x_d.*2.8e+1-t3.*xhi_v.*3.0)+(t6.*t28.*t35-t6.*t32.*t35+t7.*t31.*t35-t7.*t33.*t35).*(ddy_d+dy_d.*3.0-y.*2.8e+1+y_d.*2.8e+1-t5.*xhi_v.*3.0)-t3.*xhi_v.*(t7.*t28.*t35-t6.*t31.*t35).*3.0+t5.*xhi_v.*(t6.*t29.*t35-t7.*t30.*t35).*3.0,0.0,0.0],[3,3]);
end
