function g_q = fg_q(in1,in2,in3,in4,in5)
%FG_Q
%    G_Q = FG_Q(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:35

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
g_q = reshape([t2.*t7.*-2.0,-1.0,0.0,t3.*t7.*-2.0,0.0,-1.0,-t3.*t7.*(ddx_d+dx_d.*3.0-x.*2.0+x_d.*2.0+xhi_v-t2.*xhi_v.*3.0)+t2.*t7.*(ddy_d+dy_d.*3.0+xhi_x-y.*2.0+y_d.*2.0-t3.*xhi_v.*3.0),0.0,0.0],[3,3]);
end
