function g_xhi = fg_xhi(in1,in2,in3,in4,in5)
%FG_XHI
%    G_XHI = FG_XHI(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    17-Apr-2023 19:22:20

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = conj(theta);
t3 = cos(theta);
t4 = conj(xhi_v);
t5 = sin(theta);
t6 = cos(t2);
t7 = sin(t2);
t8 = t3.^2;
t9 = t5.^2;
t10 = t6.^2;
t11 = t7.^2;
t12 = t3.*t6;
t13 = t5.*t6;
t14 = t3.*t7;
t15 = t5.*t7;
t16 = t4.*t12.*xhi_v;
t17 = t4.*t13.*xhi_v;
t18 = t4.*t14.*xhi_v;
t19 = t4.*t15.*xhi_v;
t20 = t8.*t10.*xhi_v;
t21 = t9.*t10.*xhi_v;
t22 = t8.*t11.*xhi_v;
t23 = t9.*t11.*xhi_v;
t26 = t4.*t8.*t10;
t27 = t4.*t9.*t10;
t28 = t4.*t8.*t11;
t29 = t4.*t9.*t11;
t24 = -t17;
t25 = -t18;
t30 = t4.*t20;
t31 = t4.*t21;
t32 = t4.*t22;
t33 = t4.*t23;
t34 = t12+t19;
t35 = t15+t16;
t41 = t20+t21+t22+t23+t26+t27+t28+t29;
t36 = t13+t25;
t37 = t14+t24;
t38 = t30+t31+t32+t33;
t39 = 1.0./t38;
t40 = t39.^2;
g_xhi = reshape([(t6.*t39.*(t4.*t12+t12.*xhi_v)+t7.*t39.*(t4.*t14+t14.*xhi_v)-t6.*t35.*t40.*t41+t7.*t36.*t40.*t41).*(ddx_d+dx_d.*3.0-x.*2.8e+1+x_d.*2.8e+1-t3.*xhi_v.*3.0)+(t6.*t39.*(t4.*t13+t13.*xhi_v)+t7.*t39.*(t4.*t15+t15.*xhi_v)-t7.*t34.*t40.*t41+t6.*t37.*t40.*t41).*(ddy_d+dy_d.*3.0-y.*2.8e+1+y_d.*2.8e+1-t5.*xhi_v.*3.0)-t3.*(t6.*t35.*t39-t7.*t36.*t39).*3.0-t5.*(t7.*t34.*t39-t6.*t37.*t39).*3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3,3]);
end
