function g_xhi = fg_xhi(in1,in2,in3,in4,in5)
%FG_XHI
%    G_XHI = FG_XHI(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Apr-2023 04:38:46

theta = in1(3,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
g_xhi = reshape([t4.*t7.*-3.0-t5.*t7.*3.0,0.0,0.0,t2.*t7.*3.0,0.0,0.0,t3.*t7.*3.0,0.0,0.0],[3,3]);
end
