function h_q = fh_q(in1,in2,in3,in4,in5,in6)
%FH_Q
%    H_Q = FH_Q(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Mar-2023 00:24:45

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t12 = 1.0./r;
t10 = t2.^2;
t11 = t3.^2;
t13 = -t6;
t14 = -t8;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = t10.*xhi_v;
t18 = t11.*xhi_v;
t19 = -t15;
t20 = -t16;
t21 = t17+t18;
t23 = ddx_d+t4+t7+t13+t19+xhi_x;
t24 = ddy_d+t5+t9+t14+t20+xhi_y;
t22 = 1.0./t21;
t25 = t18.*t22.*3.0;
t26 = t17.*t22.*3.0;
t27 = b.*t2.*t12.*t22.*2.0;
t28 = b.*t3.*t12.*t22.*2.0;
t29 = t2.*t22.*t23;
t30 = t3.*t22.*t24;
t31 = t25+t26+t29+t30;
t32 = b.*t12.*t31;
h_q = reshape([t28,-t28,-t27,t27,-t32,t32],[2,3]);
end
