function h_q = fh_q(in1,in2,in3,in4,in5,in6)
%FH_Q
%    H_Q = FH_Q(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 16:10:41

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = xhi_x.*3.0;
t7 = xhi_y.*3.0;
t10 = 1.0./r;
t11 = x.*2.8e+1;
t12 = x_d.*2.8e+1;
t13 = y.*2.8e+1;
t14 = y_d.*2.8e+1;
t8 = t2.^2;
t9 = t3.^2;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = -t11;
t18 = -t13;
t19 = t8.*xhi_v;
t20 = t9.*xhi_v;
t21 = -t15;
t22 = -t16;
t23 = t19+t20;
t26 = ddx_d+t4+t6+t12+t17+t21;
t27 = ddy_d+t5+t7+t14+t18+t22;
t24 = 1.0./t23;
t25 = t20.*t24.*3.0;
t28 = t19.*t24.*3.0;
t29 = b.*t2.*t10.*t24.*2.8e+1;
t30 = b.*t3.*t10.*t24.*2.8e+1;
t31 = t3.*t24.*t27;
t32 = t2.*t24.*t26;
t33 = t25+t28+t31+t32;
t34 = b.*t10.*t33;
h_q = reshape([t30,-t30,-t29,t29,-t34,t34],[2,3]);
end
