function h_xhi = fh_xhi(in1,in2,in3,in4,in5,in6)
%FH_XHI
%    H_XHI = FH_XHI(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    21-Apr-2023 19:03:02

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*4.0;
t5 = dy_d.*4.0;
t8 = 1.0./r;
t9 = x.*4.2e+1;
t10 = x_d.*4.2e+1;
t11 = y.*4.2e+1;
t12 = y_d.*4.2e+1;
t6 = t2.^2;
t7 = t3.^2;
t13 = t2.*xhi_v.*4.0;
t14 = t3.*xhi_v.*4.0;
t15 = -t9;
t16 = -t11;
t17 = t6.*xhi_v;
t18 = t7.*xhi_v;
t19 = -t13;
t20 = -t14;
t21 = t6+t7;
t22 = t17+t18;
t24 = ddx_d+t4+t10+t15+t19;
t25 = ddy_d+t5+t12+t16+t20;
t23 = 1.0./t22.^2;
t26 = t3.*t21.*t23.*t24;
t27 = t2.*t21.*t23.*t25;
t28 = -t27;
t29 = t26+t28;
t30 = b.*t8.*t29;
h_xhi = reshape([t8+t30,t8-t30,0.0,0.0,0.0,0.0],[2,3]);
end
