function h_xhi = fh_xhi(in1,in2,in3,in4,in5,in6)
%FH_XHI
%    H_XHI = FH_XHI(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 18:59:45

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t13 = 1.0./r;
t10 = t2.*3.0;
t11 = t2.^2;
t12 = t3.^2;
t14 = -t6;
t15 = -t8;
t17 = t3.*xhi_v.*3.0;
t20 = t2.*xhi_v.*-3.0;
t18 = t11.*xhi_v;
t19 = t12.*xhi_v;
t21 = -t17;
t22 = t10-1.0;
t23 = t11+t12;
t27 = ddx_d+t4+t7+t14+t20+xhi_v;
t24 = t18+t19;
t28 = ddy_d+t5+t9+t15+t21+xhi_x;
t25 = 1.0./t24;
t26 = t25.^2;
t30 = b.*t2.*t13.*t25;
t31 = t3.*t22.*t25;
t33 = t3.*t23.*t26.*t27;
t34 = t2.*t23.*t26.*t28;
t37 = -b.*t13.*(t31+t33-t34-t2.*t3.*t25.*3.0);
h_xhi = reshape([t13+b.*t13.*(t31+t33-t34-t2.*t3.*t25.*3.0),t13+t37,t30,-t30,0.0,0.0],[2,3]);
end
