function h_xhi = fh_xhi(in1,in2,in3,in4,in5,in6)
%FH_XHI
%    H_XHI = FH_XHI(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 01:16:50

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = xhi_x.*3.0;
t7 = xhi_y.*3.0;
t10 = 1.0./r;
t11 = x.*2.8e+1;
t12 = x_d.*2.8e+1;
t13 = y.*2.8e+1;
t14 = y_d.*2.8e+1;
t8 = t2.^2;
t9 = t3.^2;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = -t11;
t18 = -t13;
t19 = t8.*xhi_v;
t20 = t9.*xhi_v;
t21 = -t15;
t22 = -t16;
t23 = t8+t9;
t24 = t19+t20;
t27 = ddx_d+t4+t6+t12+t17+t21;
t28 = ddy_d+t5+t7+t14+t18+t22;
t25 = 1.0./t24;
t26 = t25.^2;
t29 = b.*t2.*t10.*t25.*3.0;
t30 = b.*t3.*t10.*t25.*3.0;
t31 = t3.*t23.*t26.*t27;
t32 = t2.*t23.*t26.*t28;
t33 = -t32;
t34 = t31+t33;
t35 = b.*t10.*t34;
h_xhi = reshape([t10+t35,t10-t35,-t30,t30,t29,-t29],[2,3]);
end
