function g_a_3x = g_a_3x(in1,t)
%G_A_3X
%    G_A_3X = G_A_3X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Mar-2023 00:24:53

theta = in1(3,:);
t2 = cos(theta);
g_a_3x = [(t2.*(t.*2.0+3.0))./(sin(theta).^2+t2.^2);t;0.0];
end
