function g_a_1y = g_a_1y(in1,t)
%G_A_1Y
%    G_A_1Y = G_A_1Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Mar-2023 19:08:55

theta = in1(3,:);
t2 = sin(theta);
t3 = t.^3;
g_a_1y = [(t2.*(t.*6.0+t3.*2.0+t.^2.*9.0))./(cos(theta).^2+t2.^2);0.0;t3];
end
