function g_a_1x_ = g_a_1x(in1,t)
%G_A_1X
%    G_A_1X_ = G_A_1X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    12-Apr-2023 23:01:02

theta = in1(3,:);
t2 = cos(theta);
t3 = t.^4;
g_a_1x_ = [(t2.*(t3.*2.8e+1+t.^2.*1.2e+1+t.^3.*1.2e+1))./(sin(theta).^2+t2.^2);t3;0.0];
end
