function g_a_2x = g_a_2x(in1,t)
%G_A_2X
%    G_A_2X = G_A_2X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Mar-2023 19:08:55

theta = in1(3,:);
t2 = cos(theta);
t3 = t.^2;
g_a_2x = [(t2.*(t.*6.0+t3.*2.0+2.0))./(sin(theta).^2+t2.^2);t3;0.0];
end
