function g_a_4y_ = g_a_4y(in1,t)
%G_A_4Y
%    G_A_4Y_ = G_A_4Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Apr-2023 18:29:27

theta = in1(3,:);
t2 = sin(theta);
g_a_4y_ = [(t2.*(t.*4.2e+1+4.0))./(cos(theta).^2+t2.^2);0.0;t];
end
