function g_a_4y_ = g_a_4y(in1,t)
%G_A_4Y
%    G_A_4Y_ = G_A_4Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
<<<<<<< HEAD
%    13-Apr-2023 01:17:00
=======
%    12-Apr-2023 23:01:02
>>>>>>> 4600c42c8e268931e4ea11d53d8f97c1fb4bcee2

theta = in1(3,:);
t2 = sin(theta);
g_a_4y_ = [(t2.*(t.*2.8e+1+3.0))./(cos(theta).^2+t2.^2);0.0;t];
end
