function g_a_3y_ = g_a_3y(in1,t)
%G_A_3Y
%    G_A_3Y_ = G_A_3Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    26-Apr-2023 17:40:39

theta = in1(3,:);
t2 = sin(theta);
t3 = t.^2;
g_a_3y_ = [(t2.*(t.*8.0+t3.*4.2e+1+2.0))./(cos(theta).^2+t2.^2);0.0;t3];
end
