function g_a_3x_ = g_a_3x(in1,t)
%G_A_3X
%    G_A_3X_ = G_A_3X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:42

theta = in1(3,:);
t2 = cos(theta);
g_a_3x_ = [(t2.*(t.*1.0e+1+1.0))./(sin(theta).^2+t2.^2);t;0.0];
end
