function g_a_2y_ = g_a_2y(in1,t)
%G_A_2Y
%    G_A_2Y_ = G_A_2Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 01:16:59

theta = in1(3,:);
t2 = sin(theta);
t3 = t.^3;
g_a_2y_ = [(t2.*(t.*6.0+t3.*2.8e+1+t.^2.*9.0))./(cos(theta).^2+t2.^2);0.0;t3];
end
