function g_a_5x_ = g_a_5x(in1,t)
%G_A_5X
%    G_A_5X_ = G_A_5X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    16-Apr-2023 20:17:34

theta = in1(3,:);
t2 = cos(theta);
g_a_5x_ = [(t2.*2.8e+1)./(sin(theta).^2+t2.^2);1.0;0.0];
end
