function g_a_3y = g_a_3y(in1,t)
%G_A_3Y
%    G_A_3Y = G_A_3Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Apr-2023 15:12:07

theta = in1(3,:);
t2 = sin(theta);
g_a_3y = [(t2.*(t.*2.0+3.0))./(cos(theta).^2+t2.^2);0.0;t];
end
