function g_a_4x_ = g_a_4x(in1)
%G_A_4X
%    G_A_4X_ = G_A_4X(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    06-Apr-2023 20:15:42

theta = in1(3,:);
t2 = cos(theta);
g_a_4x_ = [(t2.*1.0e+1)./(sin(theta).^2+t2.^2);1.0;0.0];
end
