function g_a_2x_ = g_a_2x(in1,t)
%G_A_2X
%    G_A_2X_ = G_A_2X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    24-Apr-2023 18:29:27

theta = in1(3,:);
t2 = cos(theta);
t3 = t.^3;
g_a_2x_ = [(t2.*(t.*6.0+t3.*4.2e+1+t.^2.*1.2e+1))./(sin(theta).^2+t2.^2);t3;0.0];
end
