function g_a_4y_ = g_a_4y(in1)
%G_A_4Y
%    G_A_4Y_ = G_A_4Y(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    05-Apr-2023 02:31:20

theta = in1(3,:);
t2 = sin(theta);
g_a_4y_ = [(t2.*2.0)./(cos(theta).^2+t2.^2);0.0;1.0];
end
