function g_a_1y_ = g_a_1y(in1,t)
%G_A_1Y
%    G_A_1Y_ = G_A_1Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 01:16:59

theta = in1(3,:);
t2 = sin(theta);
t3 = t.^4;
g_a_1y_ = [(t2.*(t3.*2.8e+1+t.^2.*1.2e+1+t.^3.*1.2e+1))./(cos(theta).^2+t2.^2);0.0;t3];
end
