function g_a_5y_ = g_a_5y(in1,t)
%G_A_5Y
%    G_A_5Y_ = G_A_5Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    21-Apr-2023 19:03:06

theta = in1(3,:);
t2 = sin(theta);
g_a_5y_ = [(t2.*4.2e+1)./(cos(theta).^2+t2.^2);0.0;1.0];
end
