function g_a_1x = g_a_1x(in1,t)
%G_A_1X
%    G_A_1X = G_A_1X(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 21:21:37

theta = in1(3,:);
t2 = cos(theta);
t3 = t.^3;
g_a_1x = [(t2.*(t.*6.0+t3.*4.2e+1+t.^2.*1.2e+1))./(sin(theta).^2+t2.^2);t3;0.0];
end
