function g_a_1y = g_a_1y(in1,t)
%G_A_1Y
%    G_A_1Y = G_A_1Y(IN1,T)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 21:21:37

theta = in1(3,:);
t2 = sin(theta);
t3 = t.^3;
g_a_1y = [(t2.*(t.*6.0+t3.*4.2e+1+t.^2.*1.2e+1))./(cos(theta).^2+t2.^2);0.0;t3];
end
