function h_a_4x = h_a_4x(in1,t,in3)
%H_A_4X
%    H_A_4X = H_A_4X(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:34

h_a_4x = [0.0;0.0];
end
