function h_a_8y_ = h_a_8y(in1,t,in3,in4)
%H_A_8Y
%    H_A_8Y_ = H_A_8Y(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:38

h_a_8y_ = [0.0;0.0];
end
