function h_a_11y_ = h_a_11y(in1,t,in3,in4)
%H_A_11Y
%    H_A_11Y_ = H_A_11Y(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:38

h_a_11y_ = [0.0;0.0];
end
