function h_a_9x_ = h_a_9x(in1,t,in3,in4)
%H_A_9X
%    H_A_9X_ = H_A_9X(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:38

h_a_9x_ = [0.0;0.0];
end
