function h_a_4y = h_a_4y(in1,t,in3,in4)
%H_A_4Y
%    H_A_4Y = H_A_4Y(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Mar-2023 00:24:53

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t4 = t2.^2;
t5 = t3.^2;
t7 = t4.*xhi_v;
t8 = t5.*xhi_v;
t9 = t7+t8;
t10 = 1.0./t9;
t11 = b.*t2.*t6.*t10.*2.0;
h_a_4y = [t11;-t11];
end
