function h_a_2x_ = h_a_2x(in1,t,in3,in4)
%H_A_2X
%    H_A_2X_ = H_A_2X(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 16:10:44

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t6 = t.^3;
t9 = 1.0./r;
t7 = t2.^2;
t8 = t3.^2;
t12 = t5.*9.0;
t13 = t6.*2.8e+1;
t10 = t7.*xhi_v;
t11 = t8.*xhi_v;
t15 = t4+t12+t13;
t14 = t10+t11;
t16 = 1.0./t14;
t17 = b.*t3.*t9.*t15.*t16;
h_a_2x_ = [-t17;t17];
end
