function h_a_2x = h_a_2x(in1,t,in3,in4)
%H_A_2X
%    H_A_2X = H_A_2X(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Mar-2023 17:08:28

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t8 = 1.0./r;
t6 = t2.^2;
t7 = t3.^2;
t9 = t5.*2.0;
t10 = t6.*xhi_v;
t11 = t7.*xhi_v;
t12 = t4+t9+2.0;
t13 = t10+t11;
t14 = 1.0./t13;
t15 = b.*t3.*t8.*t12.*t14;
h_a_2x = [-t15;t15];
end
