function h_a_1x_ = h_a_1x(in1,t,in3,in4)
%H_A_1X
%    H_A_1X_ = H_A_1X(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 03:04:53

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t5 = t.^3;
t9 = 1.0./r;
t6 = t4.^2;
t7 = t2.^2;
t8 = t3.^2;
t12 = t4.*1.2e+1;
t13 = t5.*1.2e+1;
t10 = t7.*xhi_v;
t11 = t8.*xhi_v;
t14 = t6.*2.8e+1;
t15 = t10+t11;
t17 = t12+t13+t14;
t16 = 1.0./t15;
t18 = b.*t3.*t9.*t16.*t17;
h_a_1x_ = [-t18;t18];
end
