function h_a_2y = h_a_2y(in1,t,in3,in4)
%H_A_2Y
%    H_A_2Y = H_A_2Y(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    27-Apr-2023 21:21:37

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t7 = 1.0./r;
t8 = t.*8.0;
t5 = t2.^2;
t6 = t3.^2;
t11 = t4.*4.2e+1;
t9 = t5.*xhi_v;
t10 = t6.*xhi_v;
t12 = t8+t11+2.0;
t13 = t9+t10;
t14 = 1.0./t13;
t15 = b.*t2.*t7.*t12.*t14;
h_a_2y = [t15;-t15];
end
