function h_a_2x = h_a_2x(in1,t,in3)
%H_A_2X
%    H_A_2X = H_A_2X(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 01:55:35

h_a_2x = [0.0;0.0];
end
