function h_a_4y_ = h_a_4y(in1,t,in3,in4)
%H_A_4Y
%    H_A_4Y_ = H_A_4Y(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    12-Apr-2023 23:01:02

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t6 = 1.0./r;
t7 = t.*2.8e+1;
t4 = t2.^2;
t5 = t3.^2;
t10 = t7+3.0;
t8 = t4.*xhi_v;
t9 = t5.*xhi_v;
t11 = t8+t9;
t12 = 1.0./t11;
t13 = b.*t2.*t6.*t10.*t12;
h_a_4y_ = [t13;-t13];
end
