function h_a_3x = h_a_3x(in1,t,in3,in4)
%H_A_3X
%    H_A_3X = H_A_3X(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    01-Apr-2023 14:55:24

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*2.0;
t7 = 1.0./r;
t5 = t2.^2;
t6 = t3.^2;
t8 = t4+3.0;
t9 = t5.*xhi_v;
t10 = t6.*xhi_v;
t11 = t9+t10;
t12 = 1.0./t11;
t13 = b.*t3.*t7.*t8.*t12;
h_a_3x = [-t13;t13];
end
