function h_a_15x_ = h_a_15x(in1,t,in3,in4)
%H_A_15X
%    H_A_15X_ = H_A_15X(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    08-Apr-2023 17:44:39

h_a_15x_ = [0.0;0.0];
end
