function h_a_4y = h_a_4y(in1,t,in3)
%H_A_4Y
%    H_A_4Y = H_A_4Y(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:34

h_a_4y = [0.0;0.0];
end
