function h_a_3x_ = h_a_3x(in1,t,in3,in4)
%H_A_3X
%    H_A_3X_ = H_A_3X(IN1,T,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Apr-2023 22:19:30

b = in4(2,:);
r = in4(1,:);
theta = in1(3,:);
xhi_v = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.*6.0;
t5 = t.^2;
t8 = 1.0./r;
t6 = t2.^2;
t7 = t3.^2;
t11 = t5.*2.8e+1;
t9 = t6.*xhi_v;
t10 = t7.*xhi_v;
t12 = t4+t11+2.0;
t13 = t9+t10;
t14 = 1.0./t13;
t15 = b.*t3.*t8.*t12.*t14;
h_a_3x_ = [-t15;t15];
end
