function h_a_2y = h_a_2y(in1,t,in3)
%H_A_2Y
%    H_A_2Y = H_A_2Y(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Mar-2023 01:55:35

h_a_2y = [0.0;0.0];
end
