function h_a_1x = h_a_1x(in1,t,in3)
%H_A_1X
%    H_A_1X = H_A_1X(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    28-Mar-2023 23:43:34

h_a_1x = [0.0;0.0];
end
