function new_u = new_u(in1,in2,in3,in4,in5,in6)
%NEW_U
%    NEW_U = NEW_U(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    13-Apr-2023 04:00:31

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t8 = 1.0./r;
t9 = x.*1.0e+1;
t10 = x_d.*1.0e+1;
t11 = y.*1.0e+1;
t12 = y_d.*1.0e+1;
t4 = t2.^2;
t5 = t3.^2;
t6 = t2.*xhi_v;
t7 = t3.*xhi_v;
t13 = -t9;
t14 = -t11;
t17 = t8.*xhi_v;
t15 = t4.*xhi_v;
t16 = t5.*xhi_v;
t18 = -t6;
t19 = -t7;
t20 = t15+t16;
t22 = ddx_d+dx_d+t10+t13+t18;
t23 = ddy_d+dy_d+t12+t14+t19;
t21 = 1.0./t20;
t24 = t3.*t21.*t22;
t25 = t2.*t21.*t23;
t26 = -t25;
t27 = t24+t26;
t28 = b.*t8.*t27;
new_u = [t17-t28;t17+t28];
end
