function new_u = new_u(in1,in2,in3,in4,in5,in6)
%NEW_U
%    NEW_U = NEW_U(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    15-Apr-2023 16:01:09

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = xhi_x.*3.0;
t7 = xhi_y.*3.0;
t10 = 1.0./r;
t11 = x.*2.8e+1;
t12 = x_d.*2.8e+1;
t13 = y.*2.8e+1;
t14 = y_d.*2.8e+1;
t8 = t2.^2;
t9 = t3.^2;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t17 = -t11;
t18 = -t13;
t21 = t10.*xhi_v;
t19 = t8.*xhi_v;
t20 = t9.*xhi_v;
t22 = -t15;
t23 = -t16;
t24 = t19+t20;
t26 = ddx_d+t4+t6+t12+t17+t22;
t27 = ddy_d+t5+t7+t14+t18+t23;
t25 = 1.0./t24;
t28 = t3.*t25.*t26;
t29 = t2.*t25.*t27;
t30 = -t29;
t31 = t28+t30;
t32 = b.*t10.*t31;
new_u = [t21-t32;t21+t32];
end
