function new_u = new_u(in1,in2,in3,in4,in5,in6)
%NEW_U
%    NEW_U = NEW_U(IN1,IN2,IN3,IN4,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    05-Apr-2023 02:31:09

b = in6(2,:);
ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
r = in6(1,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = dx_d.*3.0;
t5 = dy_d.*3.0;
t6 = x.*2.0;
t7 = x_d.*2.0;
t8 = y.*2.0;
t9 = y_d.*2.0;
t12 = 1.0./r;
t10 = t2.^2;
t11 = t3.^2;
t13 = -t6;
t14 = -t8;
t15 = t2.*xhi_v.*3.0;
t16 = t3.*xhi_v.*3.0;
t19 = t12.*xhi_v;
t17 = t10.*xhi_v;
t18 = t11.*xhi_v;
t20 = -t15;
t21 = -t16;
t22 = t17+t18;
t24 = ddx_d+t4+t7+t13+t20+xhi_x;
t25 = ddy_d+t5+t9+t14+t21+xhi_y;
t23 = 1.0./t22;
t26 = t3.*t23.*t24;
t27 = t2.*t23.*t25;
t28 = -t27;
t29 = t26+t28;
t30 = b.*t12.*t29;
new_u = [t19-t30;t19+t30];
end
