function q_dot = q_dot(t,in2,in3,in4)
%Q_DOT
%    Q_DOT = Q_DOT(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
<<<<<<< HEAD
%    13-Apr-2023 04:00:31
=======
%    13-Apr-2023 23:10:07
>>>>>>> master

b = in4(2,:);
r = in4(1,:);
theta = in2(3,:);
wl = in3(2,:);
wr = in3(1,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = 1.0./b;
q_dot = [(r.*t2.*wl)./2.0+(r.*t2.*wr)./2.0;(r.*t3.*wl)./2.0+(r.*t3.*wr)./2.0;r.*t4.*wl.*(-1.0./2.0)+(r.*t4.*wr)./2.0];
end
