function xhi_dot = xhi_dot(in1,in2,in3,in4,in5)
%XHI_DOT
%    XHI_DOT = XHI_DOT(IN1,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    04-Apr-2023 15:12:00

ddx_d = in5(1,:);
ddy_d = in5(2,:);
dx_d = in4(1,:);
dy_d = in4(2,:);
theta = in1(3,:);
x = in1(1,:);
x_d = in3(1,:);
xhi_v = in2(1,:);
xhi_x = in2(2,:);
xhi_y = in2(3,:);
y = in1(2,:);
y_d = in3(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t2.^2;
t5 = t3.^2;
t6 = t4+t5;
t7 = 1.0./t6;
xhi_dot = [t2.*t7.*(ddx_d+dx_d.*3.0-x.*2.0+x_d.*2.0+xhi_x-t2.*xhi_v.*3.0)+t3.*t7.*(ddy_d+dy_d.*3.0+xhi_y-y.*2.0+y_d.*2.0-t3.*xhi_v.*3.0);-x+x_d;-y+y_d];
end
