function xhi_dot = xhi_dot(t,in2,in3,in4)
%XHI_DOT
%    XHI_DOT = XHI_DOT(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    14-Apr-2023 13:01:56

a1x = in4(1);
a2x = in4(2);
a3x = in4(3);
a4x = in4(4);
a5x = in4(5);
a1y = in4(6);
a2y = in4(7);
a3y = in4(8);
a4y = in4(9);
a5y = in4(10);
theta = in2(3,:);
x = in2(1,:);
xhi_v = in3(1,:);
xhi_x = in3(2,:);
xhi_y = in3(3,:);
y = in2(2,:);
t2 = cos(theta);
t3 = sin(theta);
t4 = t.^2;
t5 = t.^3;
t6 = t4.^2;
t7 = t2.^2;
t8 = t3.^2;
t9 = t7+t8;
t10 = 1.0./t9;
xhi_dot = [t2.*t10.*(a3x.*2.0+a4x.*3.0+a5x.*2.8e+1-x.*2.8e+1+xhi_x.*3.0+a2x.*t.*6.0+a3x.*t.*6.0+a4x.*t.*2.8e+1+a1x.*t4.*1.2e+1+a1x.*t5.*1.2e+1+a2x.*t4.*9.0+a1x.*t6.*2.8e+1+a2x.*t5.*2.8e+1+a3x.*t4.*2.8e+1-t2.*xhi_v.*3.0)+t3.*t10.*(a3y.*2.0+a4y.*3.0+a5y.*2.8e+1+xhi_y.*3.0-y.*2.8e+1+a2y.*t.*6.0+a3y.*t.*6.0+a4y.*t.*2.8e+1+a1y.*t4.*1.2e+1+a1y.*t5.*1.2e+1+a2y.*t4.*9.0+a1y.*t6.*2.8e+1+a2y.*t5.*2.8e+1+a3y.*t4.*2.8e+1-t3.*xhi_v.*3.0);a5x-x+a4x.*t+a1x.*t6+a2x.*t5+a3x.*t4;a5y-y+a4y.*t+a1y.*t6+a2y.*t5+a3y.*t4];
end
